### ISSUE TITLE
Missing translation in combined rank pop-ups

### ISSUE THREAD

**Issue by lostyBO** [designker/ishtar-commander-bugs#101]
The string "Total" in the combined rank pop-ups is not translated when using non-english languages.

![screenshot_20160729-000843](https://cloud.githubusercontent.com/assets/20676624/17231195/b8add958-5520-11e6-8487-04fe66dfcc1c.png)
![screenshot_20160729-000640](https://cloud.githubusercontent.com/assets/20676624/17231198/bf041268-5520-11e6-8e0b-e4d275902dad.png)

**Comment by designker** [comment]
Fixed in next version
