### ISSUE TITLE
Missing translations for "Unknown login error" text

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#102]
Two of the six homescreen languages in build 585 are missing the "Unknown login error" text.

**Comment by floatingatoll** [comment]
![photo_ - 1 23](https://cloud.githubusercontent.com/assets/92684/17231389/665da902-54d6-11e6-9e31-5a992eae535f.png)

**Comment by designker** [comment]
Check these on the spreadsheet and close them here.

**Comment by designker** [comment]
fixed
