### ISSUE TITLE
Missing Spanish translations for "Booting Ishtar OS"

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#103]
The Spain flag in build 585 produces a login animation that's missing the non-Russian localized text for the Ishtar OS boot process.

**Comment by floatingatoll** [comment]
![photo_ - 1 22](https://cloud.githubusercontent.com/assets/92684/17231355/50b9660e-54d6-11e6-82f8-74313619c74f.png)

**Comment by designker** [comment]
Should be fixed now

**Comment by floatingatoll** [comment]
Verified
