### ISSUE TITLE
German text for "consumables" collides with item count

### ISSUE THREAD

**Issue by lostyBO** [designker/ishtar-commander-bugs#105]
![screenshot_20160729-080429](https://cloud.githubusercontent.com/assets/20676624/17239321/6ece25e8-5563-11e6-8a2f-e11ec0f4085c.png)

**Comment by lostyBO** [comment]
Fixed in build 596 because you removed the item count. Was this intentional?

**Comment by lostyBO** [comment]
Nevermind, I am stupid. I did not go to the vault. The colliding text and item count is still there.

**Comment by floatingatoll** [comment]
In build 603, they don't overlap on iOS. Maybe this is Android-only?

**Comment by designker** [comment]
fixed
