### ISSUE TITLE
"Locked/Unlocked <item_name>" message not localized

### ISSUE THREAD

**Issue by cowgod** [designker/ishtar-commander-bugs#112]
When locking or unlocking an item, the word "Locked" or "Unlocked" in the status message that appears in the black bar at the bottom of the screen is not localized.

![image](https://cloud.githubusercontent.com/assets/523086/17299484/81714218-57dc-11e6-985e-38aaacd43f92.png)

**Comment by lostyBO** [comment]
Fixed in build 596 because it now only shows the item name in the bottom bar?!

**Comment by floatingatoll** [comment]
Confirmed that in build 603, it only shows the item name and not localized "locked" or "unlocked".

**Comment by designker** [comment]
fixed
