### ISSUE TITLE
"Warpriest" string is too small in Spanish

### ISSUE THREAD

**Issue by cowgod** [designker/ishtar-commander-bugs#114]
The string for "Warpriest" on the Progress tab appears very small in Spanish. Maybe it should be two lines.

**Comment by cowgod** [comment]
![image](https://cloud.githubusercontent.com/assets/523086/17307517/90bb9ed6-5803-11e6-8b70-b03c3c7106a7.jpeg)

**Comment by designker** [comment]
fixed
