### ISSUE TITLE
Certain text on Progress tab does not change when switching languages

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#118]
It seems reputation text pulled from the Bungie API, as well as Nightfall text and KF challenge info is not switched over when changing between languages in app.
No matter how many times you change languages, it will pull the text for the language used on initial startup.

Closing app and restarting forces pull of the right language.

Build 596

![screenshot_20160803-234809](https://cloud.githubusercontent.com/assets/16849366/17389752/fc3c1640-59d4-11e6-93fa-7511c9724160.png)

![screenshot_20160803-234021](https://cloud.githubusercontent.com/assets/16849366/17389682/72b6b524-59d4-11e6-9c41-0d706288688c.png)

**Comment by floatingatoll** [comment]
Does a full refresh in-app fix it?

**Comment by alexxnz** [comment]
@floatingatoll I forgot to try that. Destiny maintenance is still on-going, so I can't test that right now.
I may have done a pull to refresh, but that didn't fix anything

**Comment by alexxnz** [comment]
This seems to be resolved in Build 601
