### ISSUE TITLE
Formatting of raid checkpoints in French looks bad

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#119]
This is maybe a subjective thing, but after seeing the raid checklist in French, it didn't look right.
Would this look better if the text were center aligned beneath the corresponding icon?
![screenshot_20160804-001935](https://cloud.githubusercontent.com/assets/16849366/17390326/238e8174-59da-11e6-9df5-cad9d2c4dc5f.png)

**Comment by designker** [comment]
fixed
