### ISSUE TITLE
English characters and numbers displayed w/ wrong font on Android

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#12]
I've brought up a few examples already in the Slack, but the more I look, the more I find cases where there are English characters that are using the wrong font. I'm sure some of these examples might be irrelevant as they will be replaced with Japanese text for the full localization, but there are plenty of examples of English characters/numbers that show in the Japanese API data from Bungie. I've compiled a full list of all the places I've seen the incorrect font being used.
I can provide screenshots if needed:

- Weapon/Armor names (ex. almost, if not all, Gunsmith weapons, Plan C, Helm of Saint-14)
- Weapon/Armor perk nodes (ex. most weapon scope names, occasional flavor text)
- Weapon/Armor Level requirement number (the number 40 might be ok and I can't tell the difference, but definitely anything other than 40 shows with the wrong font)
- Transfer dialog; specifically the words "TRANSFER" and "SEND TO"
- The words "Armsday Delivery" and "Your order has arrived" on Armsday packages
- "Pull to Refresh" and "refresh" that appears in the upper-left corner (landscape) and "Refreshing" and "Transferring" messages that appear in the bottom right corner
- Almost all text in Loadouts section  (the only non-Japanese text that has the correct font is the light level number)
- English text in the Settings menu
- the Error messages that display on the bottom of the screen
- the words "Reputation" and the rank level number/rank XP bar; all the English text under the combined rank totals for each faction
- Bounties; shows up primarily in the flavor text

**Comment by designker** [comment]
Screenshot would help a ton for these issues

**Comment by alexxnz** [comment]
Ask and ye shall receive:
![screenshot_20160516-120047](https://cloud.githubusercontent.com/assets/16849366/15295381/382fb784-1b5e-11e6-88e8-9e7f594fa33b.png)
![screenshot_20160516-111821](https://cloud.githubusercontent.com/assets/16849366/15295379/382f1d24-1b5e-11e6-9370-e1335cd1a25e.png)
![screenshot_20160516-111832](https://cloud.githubusercontent.com/assets/16849366/15295377/382ec7fc-1b5e-11e6-85ac-ef60b7790e1c.png)
![screenshot_20160516-111856](https://cloud.githubusercontent.com/assets/16849366/15295378/382ecbf8-1b5e-11e6-81a5-faae273cdc6a.png)
![screenshot_20160516-111926](https://cloud.githubusercontent.com/assets/16849366/15295380/382fd764-1b5e-11e6-9b16-474d703eb094.png)
![screenshot_20160516-112003](https://cloud.githubusercontent.com/assets/16849366/15295382/38305cde-1b5e-11e6-8354-9a7a3bc90a46.png)
![screenshot_20160516-112018](https://cloud.githubusercontent.com/assets/16849366/15295383/38361dd6-1b5e-11e6-8149-7fbbad6842e6.png)
![screenshot_20160516-112117](https://cloud.githubusercontent.com/assets/16849366/15295384/383687d0-1b5e-11e6-852c-73a7b5f5ae07.png)
![screenshot_20160516-112200](https://cloud.githubusercontent.com/assets/16849366/15295385/3836cd94-1b5e-11e6-8724-3838018cac53.png)
![screenshot_20160516-112217](https://cloud.githubusercontent.com/assets/16849366/15295386/38375750-1b5e-11e6-813b-7ba2fef3a01b.png)
![screenshot_20160516-112228](https://cloud.githubusercontent.com/assets/16849366/15295387/3837ff7a-1b5e-11e6-9afa-472a4193332a.png)
![screenshot_20160516-112249](https://cloud.githubusercontent.com/assets/16849366/15295388/383a2516-1b5e-11e6-8b48-3e88bdcdfa53.png)
![screenshot_20160516-112305](https://cloud.githubusercontent.com/assets/16849366/15295389/383d890e-1b5e-11e6-8772-48bc7d0f483b.png)
![screenshot_20160516-112317](https://cloud.githubusercontent.com/assets/16849366/15295390/383de5e8-1b5e-11e6-978a-aa570f805dce.png)
![screenshot_20160516-112334](https://cloud.githubusercontent.com/assets/16849366/15295392/383f0bbc-1b5e-11e6-90e8-a450d7f766bf.png)
![screenshot_20160516-112340](https://cloud.githubusercontent.com/assets/16849366/15295393/3840126e-1b5e-11e6-9ffd-0f9e068aa2c8.png)
![screenshot_20160516-112348](https://cloud.githubusercontent.com/assets/16849366/15295391/383f0536-1b5e-11e6-9c3b-f8eb1aa8241b.png)
![screenshot_20160516-120041](https://cloud.githubusercontent.com/assets/16849366/15295394/3841142a-1b5e-11e6-8f27-ab4f0c02aae8.png)

**Comment by designker** [comment]
The issues that could be fixed have now been addressed
