### ISSUE TITLE
Incorrect writing style of raid checkpoints in German localization

### ISSUE THREAD

**Issue by lostyBO** [designker/ishtar-commander-bugs#121]
![screenshot_20160806-005435](https://cloud.githubusercontent.com/assets/20676624/17457613/4dd845bc-5bfd-11e6-921e-c0dc50370fdb.png)

The checkpoint names should all start with a capital letter in the German localization.

**Comment by designker** [comment]
fixed

**Comment by lostyBO** [comment]
Two fixed but Golgoroth and Oryx are still lowercase in build 604:
![screenshot_20160808-184520](https://cloud.githubusercontent.com/assets/20676624/17488230/a9d80a2c-5d98-11e6-822f-63f49198e8e3.png)

**Comment by designker** [comment]
fixed in 605

**Comment by lostyBO** [comment]
Now only Oryx is still in lowercase writing. Really?! :-D

**Comment by designker** [comment]
Verify fixed in the next build

**Comment by lostyBO** [comment]
Verified fixed in 66
