### ISSUE TITLE
Raid Checkpoint text not shown in landscape/tablet

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#128]
Not sure if intentional, but raid checkpoint text disappears when in landscape. Doesn't show up at all on iPad (portrait or landscape)

Still occurs in build 604

![screenshot_20160806-140103](https://cloud.githubusercontent.com/assets/16849366/17485893/0a72b4f4-5d5d-11e6-81ba-8ff9f8e0203a.png)

**Comment by designker** [comment]
This is intentional. It is unreadable
