### ISSUE TITLE
Missing localization text for reputation totals

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#129]
Both French and Spanish localizations are missing the English equivalent "Total" text for the combined reputation totals across all guardians.

As of build 604

![screenshot_20160808-114705](https://cloud.githubusercontent.com/assets/16849366/17486484/fbc27140-5d5e-11e6-95f8-990d4b173bc8.png)
![screenshot_20160808-114930](https://cloud.githubusercontent.com/assets/16849366/17486483/fbc095b4-5d5e-11e6-97fd-d530345392a5.png)

**Comment by designker** [comment]
fixed in 605
