### ISSUE TITLE
Text runoff in Progress tab

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#131]
Certain text, especially in the other languages, can run past the vertical divider in the progress tab. I've taken screenshots of the examples I've seen so far.

Build 604

![screenshot_20160806-140103](https://cloud.githubusercontent.com/assets/16849366/17487163/a9ddd56a-5d61-11e6-93da-fb72c6618846.png)
![screenshot_20160808-120421](https://cloud.githubusercontent.com/assets/16849366/17487164/a9de5544-5d61-11e6-99aa-6e2ce7e803e9.png)
![screenshot_20160808-120608](https://cloud.githubusercontent.com/assets/16849366/17487165/a9e12454-5d61-11e6-9223-279e75a33445.png)

**Comment by designker** [comment]
fixed in 605
