### ISSUE TITLE
Subclass selector might need more spacing / Should be left-aligned

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#132]
Particularly in landscape, it feels like the subclass name runs too close to the header for Helmets (screenshot below)

And this is maybe personal choice, but the subclass selector should be reversed to bring it in line with the rest of the UI. Meaning that the equipped subclass should appear on the left, as it is with the rest of the items.

I think the only reason it appears right-aligned in-game is because the rest of the items in that column are also right-aligned.
![screenshot_20160808-120644](https://cloud.githubusercontent.com/assets/16849366/17487474/f83b4a3e-5d62-11e6-9ec8-e2793d4598da.png)

**Comment by designker** [comment]
fixed
