### ISSUE TITLE
Subclass details popup is gigantic

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#133]
Keep forgetting about this one, but particularly on iPad, the pop-up is ginormous compared to any other pop-up in the app.

![img_0044](https://cloud.githubusercontent.com/assets/16849366/17487559/6371b2b6-5d63-11e6-8191-37531710309a.PNG)

**Comment by designker** [comment]
No plans to fix this. It is jam packed with icons
