### ISSUE TITLE
"Equip max light" doesn't correctly handle artifacts when lower than level 40

### ISSUE THREAD

**Issue by cowgod** [designker/ishtar-commander-bugs#139]
My "Equip max light" option worked fine from level 1-20 or so, but it stopped working recently. It correctly transfers and equips the necessary gear, but then gives the error "Maxed light failed, 9 of 10 transferred", and the screen goes blank:

![image](https://cloud.githubusercontent.com/assets/523086/17567729/97b967f6-5f0e-11e6-9637-b6afebf84d5b.png)

I do have hunter artifacts in my vault, since I previously had a hunter and deleted it.

**Comment by floatingatoll** [comment]
Slack discussion narrowed this down to "9 of 10 transferred" being probably being wrong for a character above level 20, but below level 40 (not shown in screenshot).

**Comment by floatingatoll** [comment]
(This could also be a theoretical bug with class items, IF you somehow only had a faction class item and no other items, and then changed factions and hit Max Light. I don't have any way to test this, though.)

**Comment by designker** [comment]
verify fixed err a couple of builds back

**Comment by designker** [comment]
Verified myself
