### ISSUE TITLE
Text overlaps UI on Settings screen (iPad)

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#14]
First screenshot is older, but is currently formatted exactly the same
![img_0029](https://cloud.githubusercontent.com/assets/16849366/15292886/5e161e8a-1b53-11e6-876c-fa321e2250b6.PNG)
![img_0031](https://cloud.githubusercontent.com/assets/16849366/15292887/5e16bb4c-1b53-11e6-8c5f-05ac22ccd1c5.PNG)

**Comment by designker** [comment]
Fixed
