### ISSUE TITLE
'Undefined' for Blast Radius and Velocity stats (ES,PT-BR,FR)

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#142]
Text label for the Blast Radius and Velocity stats for rocket launchers show as 'Undefined' in the following languages:

Spanish
French
Brazilian Portuguese

Build 613

**Comment by alexxnz** [comment]
Spanish screenshot
![screenshot_20160812-203232](https://cloud.githubusercontent.com/assets/16849366/17641653/ddb6cbba-60f6-11e6-8015-6536017c01d1.png)

**Comment by designker** [comment]
Verify fixed in 616. BTW it is 'es' for spanish and 'pt-br' for Portuguese-Brazil

**Comment by alexxnz** [comment]
Verified this is fixed in build 616 for all affected languages
