### ISSUE TITLE
Equipped weapon details appears cutoff at top

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#143]
Tall weapon detail popups, for the equipped weapon, has the top of the white border cutoff by the top of the screen (at least on Android)

Build 613

![screenshot_20160813-012804](https://cloud.githubusercontent.com/assets/16849366/17641657/1b448dd2-60f7-11e6-9768-c5543d4f2474.png)

**Comment by floatingatoll** [comment]
If you swipe left or right through the other items in that slot, are any
other items cut off? Do they all share the same lower or upper border
position, perhaps?

**Comment by designker** [comment]
Verify fixes in 616

**Comment by alexxnz** [comment]
Verified fixed in build 616

To answer your question @floatingatoll , none of the other items were cutoff. I think with the app was sitting certain height popups flush with the top of the screen, and forgot to take into account the added height of the Equipped border.
