### ISSUE TITLE
Locked/Unlocked text not separated with space

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#144]
For certain localizations, there is no space separating the "Locked/Unlocked" text from the item name (Build 613). Below is the French example of this.

The languages currently affected:

French
Italian
Spanish

![french locked](https://cloud.githubusercontent.com/assets/16849366/17641673/15b416de-60f8-11e6-8d7f-a5757fb8de95.png)

**Comment by designker** [comment]
verify fixed in 616. This is fixed properly now so the items in the spreadsheet don't need a space

**Comment by alexxnz** [comment]
Verified fix in build 616 for all affected languages
