### ISSUE TITLE
Missing Locked/Unlocked localization text (BR)

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#145]
Brazilian Portuguese localization is missing the text for Locked/Unlocked (Build 613)

![portuguese locked](https://cloud.githubusercontent.com/assets/16849366/17641680/5de760e6-60f8-11e6-9e8e-3e5410784fb3.png)

**Comment by floatingatoll** [comment]
@alexxnz says it's fixed in build 661
