### ISSUE TITLE
Locked/Unlocked strings after item name in DE

### ISSUE THREAD

**Issue by lostyBO** [designker/ishtar-commander-bugs#146]
In german the item name in the message should be placed before the localized strings for locked/unlocked.

![screenshot_20160813-104352](https://cloud.githubusercontent.com/assets/20676624/17642382/49f1792c-6144-11e6-841b-a8ac650b1066.png)

In this example it should be "NIRWENS GNADE GESPERRT".

**Comment by designker** [comment]
Should be fixed in 616

**Comment by lostyBO** [comment]
Verified fixed in 616
