### ISSUE TITLE
Halloween Masks are not sorted by rarity

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#147]
Pretty sure this only affects Android as the build is rarely updated for that platform.
Apologies if this has already been fixed in iOS

Build 616

![screenshot_20160815-140101](https://cloud.githubusercontent.com/assets/16849366/17673861/08cdf53e-62f1-11e6-983b-71ec3eda29e3.png)

**Comment by floatingatoll** [comment]
Also in this screenshot, the three engram masks should be sorted together,
in order of rarity (per recent sorting discussions).

**Comment by designker** [comment]
Is this fixed? I don't have the items to test

**Comment by alexxnz** [comment]
It seems they are are now grouped by rarity as of Build 619, but I'm not sure I agree with the way they're sorted (nitpick, I know)

Like why is the Cryptarch mask sitting in the middle of the raid bosses? And the legendary engram mask should come before the rare engram mask  to be in line with the rest of the sorting the app currently does.

![screenshot_20160817-150244](https://cloud.githubusercontent.com/assets/16849366/17749537/158cdf78-648c-11e6-8931-86d68139d438.png)

The reported issue is resolved, but I'll let you decide whether to close this issue out.
