### ISSUE TITLE
Court of Oryx Bounties have a rarity where they shouldn't

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#148]
This has been around for a while, but for some reason the CoO bounties have a rarity of 'Basic'. This doesn't appear in-game.
The color is also different than what appears in-game, but I'm not sure if that's something you want to pursue. I can provide in-game screenshot if needed.

Build 619

![screenshot_20160816-093355](https://cloud.githubusercontent.com/assets/16849366/17700682/d9448c2a-6394-11e6-9ab3-b3f3d2ceb3c1.png)

**Comment by designker** [comment]
Fixed
