### ISSUE TITLE
questTracked works differently on quests

### ISSUE THREAD

**Issue by designker** [designker/ishtar-commander-bugs#153]
instead of the 'state' property there is a 'tracked' property. So setItemQuestTrackedState() needs to update this. Probably also detailPopup needs to look to this different property to show the correct icon in the top right

**Comment by floatingatoll** [comment]
(Nigel says this would be necessary to solve someday if he chose to implement tracking/untracking quests in Ishtar.)

**Comment by designker** [comment]
Won't fix for D1
