### ISSUE TITLE
Verify localization of Progress tab against Destiny 2.4.0

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#154]
"Quest menu has been changed and renamed to Progress" per https://www.bungie.net/en/News/Article/45172/7_Destiny-Update-090816 so localization may need to be updated to match their choices

**Comment by lostyBO** [comment]
They will also change the german word for "quest" and will reuse the english word. The translated strings for quests will need to be updated.

**Comment by floatingatoll** [comment]
@designker did you switch to using the strings from Destiny now that they match yours? if so, this can be closed
