### ISSUE TITLE
mark completed quests steps as complete

### ISSUE THREAD

**Issue by designker** [designker/ishtar-commander-bugs#155]

**Comment by floatingatoll** [comment]
I see completed quest steps as complete on my quests on build 661, RoI:

The Road to King's Fall - step 1 complete, step 2 underway, Slay Golgoroth completed within that.

Path of the Voidwalker - steps 1-7 complete, 8 underway, neither sub-step completed.

Sparrow Racing - step 1 complete, 2 underway, substep Races Finished 0/5 not complete.

Was this fixed?
