### ISSUE TITLE
App crashes using Android 7.0 multi-window feature

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#156]
Probably an edge case, but opening for awareness.
Loading the app in multi-window mode and resizing tends to crash the app (video below).

I know it is possible to disable this feature on the app itself, but unsure if this is something you would want to support.
Here is an Android dev page detailing the feature: [https://developer.android.com/guide/topics/ui/multi-window.html](https://developer.android.com/guide/topics/ui/multi-window.html)

Video:
[https://dl2.pushbulletusercontent.com/4ZZZC1s5KDBvZeWxr21imSvG5tXNWLQm/2016_08_30_16_23_52.mp4](https://dl2.pushbulletusercontent.com/4ZZZC1s5KDBvZeWxr21imSvG5tXNWLQm/2016_08_30_16_23_52.mp4)

**Comment by floatingatoll** [comment]
'tends'? only sometimes?

**Comment by designker** [comment]
I have no way of testing this. Closed for now.
