### ISSUE TITLE
feature request / re-ordering of loadouts

### ISSUE THREAD

**Issue by untidey** [designker/ishtar-commander-bugs#159]
Allow for drag-and-drop re-ordering of loadouts when in the edit view of the loadouts panel. Perhaps limit this functionality to the overall vault view of loadouts to prevent confusion.

**Comment by untidey** [comment]
Sorry Nigel, I don't seem to be able to add the feature request label to this issue. Perhaps that is repository admin functionality only? Modified issue title to be clear this isn't a bug report.

**Comment by floatingatoll** [comment]
@designker says occasionally that there's a loadout rewrite due sometime, closing out this feature request
