### ISSUE TITLE
Copy/Paste options not available on Android

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#16]
Text selection on the Android app seems to emulate native iOS text selection. Touch and holding text in app brings up an iOS-like magnifying glass, which normally doesn't exist in Android. Selection markers are also from iOS instead of native Android.

I can select text, but there is no option for copy, paste, etc., although in one of the attached screenshots, you can see what I assume is the copy/paste menu, but it appears above the viewable area.

And somewhat related, once I bring up the keyboard to at least edit a loadout name, I can no longer select text anymore. I can only move the cursor placement. I have to back out of the edit screen and go back in to select text again.
![screenshot_20160516-121404](https://cloud.githubusercontent.com/assets/16849366/15295942/1abc3544-1b61-11e6-95f1-ab937f845dd2.png)
![screenshot_20160516-122306](https://cloud.githubusercontent.com/assets/16849366/15295943/1abd4baa-1b61-11e6-994c-98ab783e3317.png)

**Comment by alexxnz** [comment]
Also, just noticed that copy/paste does not work on the web view for logon either. I imagine that will make it painful for people that rely on password managers and/or two-factor authentication.

**Comment by designker** [comment]
Unable to fix. Framework issues
