### ISSUE TITLE
Iron Lord's Legacy shows subheading as '"null"

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#161]
Looking at the Iron Lord's Legacy item in app, the subheading is shown as "null"

In game, there is no subheading for this item (ex. consumable, material)

![image](https://cloud.githubusercontent.com/assets/16849366/18723352/34d83a4a-8006-11e6-97ad-fcecdbf75e94.png)

**Comment by designker** [comment]
Fixed
