### ISSUE TITLE
Max Light automated loadout should consider new artifact requirements

### ISSUE THREAD

**Issue by cowgod** [designker/ishtar-commander-bugs#162]
When trying to "Max Light" on a character that hasn't yet "Attuned" an artifact, Ishtar tries to equip it but is unable to.

**Comment by cowgod** [comment]
![img_1151](https://cloud.githubusercontent.com/assets/523086/18728590/da16cef8-801b-11e6-984c-5238a35e4056.PNG)

**Comment by floatingatoll** [comment]
@designker said on Slack a while back that there's nothing in the API that makes it possible to tell whether or not the artifact is equippable and so this can't be prevented.
