### ISSUE TITLE
Damage type node is not matching actual damage types on some weapons

### ISSUE THREAD

**Issue by theebanka** [designker/ishtar-commander-bugs#163]
I currently only have this problem on one weapon (from Archon Forge) so I have no idea what triggers this or how widespread it is... here is a reminder screenshot
![slack for ios upload](https://cloud.githubusercontent.com/assets/10566478/18813987/c4b7b2b8-82c1-11e6-9d32-0051bcb15fc6.jpg)

**Comment by floatingatoll** [comment]
Of my 4 special weapons from ROI, one sniper (of 2) shows it.

**Comment by floatingatoll** [comment]
![img_4434](https://cloud.githubusercontent.com/assets/92684/18816778/f076de72-8304-11e6-9040-5cf920971958.PNG)

**Comment by floatingatoll** [comment]
I also found a void heavy that shows as arc. Other void weapons are okay.

![img_4435](https://cloud.githubusercontent.com/assets/92684/18816787/1f327cd0-8305-11e6-9e3b-547c71bcb603.PNG)

**Comment by designker** [comment]
This is bungies bug, not mine https://www.bungie.net/en/Clan/Post/39966/213743863/0/0

**Comment by floatingatoll** [comment]
Bungie fixed their bug in the latest patch, apparently
