### ISSUE TITLE
Item comparison on tablet could be bigger

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#166]
Not a bug, but wanted to bring attention to this.

On a tablet, comparing items shows much smaller popup windows than displaying the details of a single item.
There seems to be enough space to make the 2-3 popups bigger so they're more readable.

Below are screenshots from my iPad (build 646)

![std details view](https://cloud.githubusercontent.com/assets/16849366/18823201/babd7012-8385-11e6-8226-42a399835809.PNG)
![comparison view](https://cloud.githubusercontent.com/assets/16849366/18823205/bf84292e-8385-11e6-9402-ed8adbcd436e.PNG)

**Comment by floatingatoll** [comment]
"not a bug" - bring feature requests to nigel in #general
