### ISSUE TITLE
In landscape mode, manifest loading text is missing black background

### ISSUE THREAD

**Issue by cowgod** [designker/ishtar-commander-bugs#167]
When starting the app in portrait mode, it starts with a black screen that displays the statuses messages about loading the manifest data. In landscape mode, this text is printed over the application window itself, without the black background.

**Comment by floatingatoll** [comment]
Cow says he no longer sees this.

**Comment by designker** [comment]
I am sure this issue is still there, but will go away with some other changes I have planned.
