### ISSUE TITLE
Comparison windows size difference and potential overlap

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#17]
I'm unsure if this is intentional or not, but I noticed a fairly substantial difference in font size between two weapons on comparison (see first screenshot). I know the windows will scale to fit, but the effect seemed exaggerated when looking at the device.

I also noticed that when I swiped back to the perk list, it caused the comparison windows to overlap (screenshot 2). When I opened the comparison windows, it initially showed me the perk tree, which is usually my default.
![screenshot_20160518-172058](https://cloud.githubusercontent.com/assets/16849366/15376053/ba090da0-1d20-11e6-836a-836006985ffd.png)
![screenshot_20160518-172104](https://cloud.githubusercontent.com/assets/16849366/15376052/ba08967c-1d20-11e6-9016-e25eebe9b154.png)

**Comment by designker** [comment]
fixed
