### ISSUE TITLE
UX broken for text/perks swap button on various items

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#174]
Screenshots follow, build 661.

![photo_ - 1 32](https://cloud.githubusercontent.com/assets/92684/19216016/eccbbb90-8d62-11e6-9c46-8c6ed8c86d5c.png)
![photo_ - 3 2](https://cloud.githubusercontent.com/assets/92684/19216019/ed30d3a4-8d62-11e6-9e1a-9a7dc2b8f2f5.png)
![photo_ - 4 1](https://cloud.githubusercontent.com/assets/92684/19216017/ecdedb76-8d62-11e6-983a-c01b93552a97.png)
![photo_ - 5](https://cloud.githubusercontent.com/assets/92684/19216018/ed045ad6-8d62-11e6-9f01-1b7a99a8faea.png)
![photo_ - 1 35](https://cloud.githubusercontent.com/assets/92684/19216086/5c6d2adc-8d64-11e6-8322-6194c4785316.png)

**Comment by floatingatoll** [comment]
Fixed for vehicles, perk-less class items, starter ghosts.

*Not* fixed for SRL equipment, Young Wolf's Howl (above).

**Comment by floatingatoll** [comment]
*Not* fixed in 664 for Young Wolf's Howl.

Fixed in 664 for SRL equipment.

Observed that perk-less class items now have an extra block of whitespace at the end. Unsure if this was introduced by 662 or 664:

![photo_ - 1 36](https://cloud.githubusercontent.com/assets/92684/19244460/3a3b6a96-8ed1-11e6-8e49-f58db2d7c30b.png)

**Comment by designker** [comment]
Won't be fixing the final issue
