### ISSUE TITLE
Tracked bounties don't show the green corner icon in on the Progress tab

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#176]
Screenshot is of long-press of the top-left bounty in the grid (I tracked it in-game), showing tracked corner icon in detail view, but not in the grid.

![photo_ - 1 34](https://cloud.githubusercontent.com/assets/92684/19216059/ea09e75a-8d63-11e6-9a03-a725afbd5695.png)

**Comment by designker** [comment]
Shows fine for me and the screenshot looks correct as well.
