### ISSUE TITLE
Thorn quest shows x/125 in Ishtar rather than x% like the game does

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#179]
No one wants to provide a screenshot and I don't have the Thorn quest, but I assume it's just another place to apply the same %-or-number logic that bounties use.

**Comment by floatingatoll** [comment]
VThornheart says that the ```displayValue``` property ought to contain the correct thing to display ("0/500" or "0%" or whatever), but it's broken in the current API for everything but record books. However, the ```valueStyle``` property *is* working in the current API, enum { ```1 fraction```, ```2 checkbox```, ```3 percentage``` }, so rather than the current ```> 500``` logic, you should be able to just use valueStyle to test for percentage-or-fraction. Supposedly.

**Comment by floatingatoll** [comment]
https://www.bungie.net/en/Clan/Post/39966/215408202/0/0 will have a formaly reply about this shortly, as well.

**Comment by designker** [comment]
Unable to fix for now

**Comment by floatingatoll** [comment]
VThornheart replied at https://www.bungie.net/en/Forums/Post/215408737?sort=0&page=0&path=1 –

> Yeah, so the contract class for objectives has a property that is supposed to give this to you automatically: the "displayValue" property. However, it is currently only being populated in record book objectives. I filed a bug to get it fixed so it is always populated, which should help with this.
> In addition, the valueStyle property of the Objective Definition in the manifest database should be usable to form your own code for rendering the appropriate UI. It's an enum value where:
> 1 = Fraction
> 2 = Checkbox
> 3 = Percentage
> There is also a 4th state, 0 = Automatic. In BNet's UI, we show Automatic as Checkbox: but that's a bit of an oversimplification of the real situation. As part of fixing this bug, I'll look into exposing more information so that the Automatic state is less of a guess.

**Comment by designker** [comment]
Closing due to Bungie historically never fixing this kind of issue
