### ISSUE TITLE
If an un-attuned artifact is on a character, Ishtar sometimes tries to equip it if that character's equipped artifact is moved to another character.

### ISSUE THREAD

**Issue by tehtrav** [designker/ishtar-commander-bugs#181]
[via @downpressor on Slack](https://ishtar-commander.slack.com/archives/general/p1476456316002790)

> what i realized was happening is that Ishtar was trying to swap out that artifact on the alt (because they had it equipped) with an artifact in their inventory that they were not attuned to (I think). (edited)
> 
> BUT
> 
> they had like 5-6 other normal artifacts for their class that could have been equipped in its place
> 
> so to get around it I had to manually equip a generic warlock artifact to the character first, then move the iron lord artifact to another character
> 
> otherwise it just gave an error over and over

**Comment by floatingatoll** [comment]
Nigel mentioned on Slack that bungie API offers no real way to detect if it's attuned or not, and so it can't really treat the artifact differently and has to simply try and equip it and hope it works out. I read that as "nothing that can be one here, sorry", but Nigel can reopen if he wants to do something more.
