### ISSUE TITLE
gather prefers incomplete stacks over complete stacks, when character doesn't have enough room

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#184]
Build 691: Character has 19 of 20 materials slots in use, 1 stack of 200 spinmetal on char. Vault has 4 stacks of 200 spinmetal, 55 spinmetal.

Selecting the character 200 stack Gather results in the 55 stack being transferred in and 4 (expected) "no room" warnings.

I should end up with 2 stacks of 200 spinmetal on char. It should break up existing stacks to do so, and prefer 200 stacks over 55 stacks when consolidating.

**Comment by designker** [comment]
Not going to fix for D1, may revisit for D2
