### ISSUE TITLE
distribute leaves stacks in the vault when the destination doesn't have enough room

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#185]
distributing wants to send 200+154 spinmetal to each of my 3 characters, but i intentionally filled one of them to 19/20 slots (without spinmetal) before distributing from the vault.

it send the 154 stack first, and then tried and failed to send the 200 stack, to the 19/20 character. the usual "no room" error bar shows, and it left a 200 stack in my vault.

perhaps it should transfer the 200 stack first, and distribute the remainder to the other characters (since they have incomplete 154 stacks, and room to hold it)?

build 691

**Comment by designker** [comment]
Not going to fix due to zero complaints in the wild. May revisit this for D2
