### ISSUE TITLE
manual item transfers take precedence over in-progress distribute/gather

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#188]
if i start a distribute/gather on a materials slot item and then quickly transfer another materials item while it's running, my manual transfer is processed _during_ rather than _after_ the distribute/gather

i was able to cause a "slots full" error a la #185 by moving something other than the material being distributed, and an "item not found" error by moving one of the stacks of the material being distributed.

note that it's really difficult to do this because you made transfers very efficient

**Comment by designker** [comment]
Not going to fix for D1
