### ISSUE TITLE
Classified items not showing in General Vault (maybe others not sure)

### ISSUE THREAD

**Issue by theebanka** [designker/ishtar-commander-bugs#192]
I did a bit more testing and anything classified that would go into the general section of the vault (shaders, consumable, items etc) do not show at all once in the vault. I just tested this with both a shader and a tiny box of raisins... they show properly as the "?" Icon when on the character but don't show in the vault which leads to vault miscounts. This may extend past the General vault section but without classified weapons or armor to test with I can't be sure. 

By not showing the classified items in the vault the number of items it contains doesn't match the in game amount. 

Here was you're response from slack:
There is nothing I can do about that. I reported why to Bungie. However still raise a bug as I can fix the vault count being wrong

**Comment by designker** [comment]
I am going to close this. I cannot think of any bug bungie have ever fixed so don't hold out much hope here.
