### ISSUE TITLE
Loadout doesn't make room for items when slots are full

### ISSUE THREAD

**Issue by SublymeRick** [designker/ishtar-commander-bugs#196]
Basically I want to remove all the stuff on the current character when applying a new load out to the character sometimes there's a lot of things on the character which causes problems when applying the new load out it would be nice if there was an option to have the system clear the player or character before applying the new load out

**Comment by floatingatoll** [comment]
Updating title to try and reflect what I understand the problem to be. If wrong, feel free to correct me.

**Comment by SublymeRick** [comment]
Well, sort of... What I'm trying to say is, rather than just "making room" I would like the option to create "clean loadouts" where ONLY the armor and weapons I have configured in the loadout exist on the character when applied. Meaning if a piece is on the character that is not part of the loadout it would get removed....

The way I was trying to explain it before is  to clear all weapons and armor prior to applying a selected loadout.

I figured this should be a "toggle" when creating the loadout so not every is forced to run loadouts this way if they do not want to.

**Comment by designker** [comment]
This is a neat idea, but not the kind of thing for Ishtar right now. The loadouts are intentionally quite simple and a clean way to add this kind of option isn't clear. Loadouts will be getting an overhaul in the future so I will keep this kind of thing in mind.
