### ISSUE TITLE
Back button functionality with Quests

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#197]
I believe this only affects Android, but if you open a quest, and then open one of the quest steps to view its details, and then press the back button, the app closes the quest view entirely. I would expect the back button to just close the individual quest step details, and bring me back to the details of the entire quest.

The more interesting side effect of this is if you use the back button to back out of the quest while looking at one of the quest steps, the next quest you open up will show the quest step from that first quest.

I've attached some screencaps to better illustrate this. The first is one of the titan quests I was examining, and then I switch to the Thorn quest on a different character.

Build 722

![screenshot_20161112-010818](https://cloud.githubusercontent.com/assets/16849366/20236116/ec9b1cb8-a876-11e6-9109-14de7c3ca2e3.png)
![screenshot_20161112-010832](https://cloud.githubusercontent.com/assets/16849366/20236118/f0d6b71a-a876-11e6-994f-87739f93d7d3.png)

**Comment by designker** [comment]
These kind of back bugs are super helpful. Thanks for reporting these. They are now really easy to fix with the new back system in Ishtar.

**Comment by designker** [comment]
Fixed
