### ISSUE TITLE
Missing "Speed" for Sparrow details

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#20]
Ishtar app is missing the word "Speed" next to the speed number for sparrows.
I've included an in-game screenshot for comparison

![destiny_20160516134025](https://cloud.githubusercontent.com/assets/16849366/15456829/113b1bd2-204a-11e6-97b9-848d15dca692.jpg)

**Comment by designker** [comment]
fixed for build 469
