### ISSUE TITLE
In maximizing LL do not replace a class item with another of the same LL

### ISSUE THREAD

**Issue by philipmat** [designker/ishtar-commander-bugs#204]
Repro:
- equip a LL400 (faction) class item that is not fully upgraded.
- ensure you have a LL400 class item that is fully upgraded
- execute Maximize Light action, either directly or through Harvest Engrams

Result: the fully upgraded class item replaces the faction class item, even though both are of the same light and thus the switch does not contribute towards raising the LL.

Expected: the faction class item should not have been swapped out.

**Comment by floatingatoll** [comment]
Nigel said on Slack that this is intentional, as otherwise Max Light on alts ends up leaving them with unleveled gear. Closing based on that, but obviously he could reopen any time if y'all change your mind.
