### ISSUE TITLE
Show stat effects on weapons when long pressing node

### ISSUE THREAD

**Issue by therarecommoner** [designker/ishtar-commander-bugs#205]
Create a UI that shows a pseudo selection of a perk slot, irrespective of what's currently equipped or unlocked to show the stat effect on a piece of gear. An unused interaction pattern is the long press on gear nodes. Suggest that when the user long presses on a gear node the descriptive text for that node disappears, and the user enters pseudo-node selection mode. Upon entering this mode, the user is able to tap various nodes to see the variance in stat bars and absolute values as a result of that change. This would enable users to check the actual differences among same gear drops, mostly for weapons, as unselected and selected node value changes are displayed for armor/shells. I know I'd love it ;)

**Comment by floatingatoll** [comment]
Cool idea! As with the other one, feature requests aren't tracked as github issues, but that's no judgement on whether or not it's worth doing.
