### ISSUE TITLE
Create gear menu setting to show max possible armor stat

### ISSUE THREAD

**Issue by therarecommoner** [designker/ishtar-commander-bugs#206]
On the right of a piece of armor's unselected and selected INT/DIS/STR rolls, show, in yellow, the absolute max value available for that armor. This would allow a user with a quick, albeit reparative, but in this case, absolute distance between available and max stat roll for that class of gear.  While the relative quality score for a bit of gear is helpful for quickly determining it's value, having the absolute max it could have rolled for is also helpful to for one example to quickly compare absolutely two duplicate pieces of gear.

**Comment by floatingatoll** [comment]
Thanks for the idea. Feature requests aren't tracked through github, so I'm closing this now.

**Comment by therarecommoner** [comment]
Quick follow-up, where do feature requests live? Would love to see them if there's a place. Could set you up with a channel for them if you don't have one. Surely the community would love it, even if your time is limited to complete them. Also the case of getting ideas going...

**Comment by floatingatoll** [comment]
They live in the creator's head, and nowhere else on record that any of us are aware of. If you Reddit, look through the past few /r/destinythegame Ishtar release announcements; the comments may well already cover your feature - and if they do, he's aware of the request.

 - R.
