### ISSUE TITLE
Long-press modal shows two Ornaments as active

### ISSUE THREAD

**Issue by tehtrav** [designker/ishtar-commander-bugs#207]
Both my MIDA's ornaments are unlocked but only Special Ops (top one) should be active.

![img_0351](https://cloud.githubusercontent.com/assets/351975/20891574/281c85c8-bad9-11e6-9181-e23561349072.PNG)

**Comment by floatingatoll** [comment]
Also: Telesto, Truth, Invective

**Comment by designker** [comment]
Not going to fix for D1
