### ISSUE TITLE
Grading changes due to glass needles not reflected until app restart

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#209]
![before restart](https://cloud.githubusercontent.com/assets/92684/21083413/ec9d6b7c-bfa4-11e6-8d22-8b4bf2a42e4a.jpg)

![after restart](https://cloud.githubusercontent.com/assets/92684/21083414/ee1bd51a-bfa4-11e6-9eb2-fa650d87fb20.jpg)

**Comment by designker** [comment]
Not going to fix for D1
