### ISSUE TITLE
Year 1 armor displays incorrect max values

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#21]
Max stat values shown in app for Y1 items differ than what appear in-game.
I've also noticed Ishtar does not show all mandatory perk upgrades for Y1 items, treating the secondary (or even tertiary) node ability as an optional slot. (notice the missing grenade perk in-app compared to in-game below)

![img_0036](https://cloud.githubusercontent.com/assets/16849366/15456968/0b66ce32-204e-11e6-9413-2dd18dce3aa7.PNG)
![destiny_20160516133230](https://cloud.githubusercontent.com/assets/16849366/15456969/0d90a48a-204e-11e6-809c-f8eb27a7184c.jpg)

**Comment by designker** [comment]
Sorry. Won'f be fixing year one weapon issues
