### ISSUE TITLE
Consumable sort bugged w/ Classified items

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#210]
I noticed that consumables weren't sorted for me anymore, so I decided to test a theory. The first screenshot shows my original inventory. I then deposited the classified items to the vault in-game, and allowed the app to auto-refresh after some time. (I also opened a Dawning package, hence the extra items)
After the refresh, sort seems to be normal, but classified item icons don't appear in Ishtar vault. However, item count seems accurate.

Build 752

**Before**
![before](https://cloud.githubusercontent.com/assets/16849366/21303634/9dbf242a-c58d-11e6-859d-e8c242739925.PNG)

**After**
![after](https://cloud.githubusercontent.com/assets/16849366/21303635/a28f746e-c58d-11e6-9857-458cac0193b1.PNG)

**Comment by designker** [comment]
This isn't a bug. On characters I know which section a classified item belongs to. However on the vault I only know which vault it is in, not which section. Therefore the best I can do is show the correct count.

**Comment by floatingatoll** [comment]
Is it expected as part of this that sorting of primary/special/heavy synths doesn't occur when a classified item is present?

**Comment by designker** [comment]
I can see the issue. I fixed it for the next release.
