### ISSUE TITLE
Swipe to equip breaks when swiping right to left

### ISSUE THREAD

**Issue by stevennic22** [designker/ishtar-commander-bugs#211]
Swipe to equip works in one direction (left to right swipe), but still shows the indicator (and won't work) when swiping right to left.

[Video example](https://dl.dropboxusercontent.com/u/156834/2017-01-21_12-04-41.mp4)

**Comment by floatingatoll** [comment]
iOS as well, today's build.

**Comment by designker** [comment]
Fixed
