### ISSUE TITLE
Overlapping panes on startup due to a well-timed tap

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#212]
During a fresh startup, I tapped on the Inventory or Progress tab at *just* the perfect moment during startup to trigger a pane loading while another pane was loading.

![img_5089](https://cloud.githubusercontent.com/assets/92684/22237146/be4aa582-e1be-11e6-818d-1b170379cb1b.jpg)

I was able to swipe left and right and operate one of the layers, until I eventually swiped the "top" pane (that was swiping) to the same as the "bottom" pane (that was stuck), at which point the app clearly had a moment with itself and self-healed.

After that, it worked fine. Screenshot taken shortly after updating on December 22, 2016 at 17:12:26 -0800.

**Comment by designker** [comment]
Not going to fix
