### ISSUE TITLE
Vertical alignment of Russian text at login screen is slightly low

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#213]
The distance from the C in "Connecting" to the П in "После" is a couple pixels too large, compared to the the distance from the "U" in "Unable" to that same П. Screenshot dated Dec 22, 2016.

![img_5091](https://cloud.githubusercontent.com/assets/92684/22237281/9e7df758-e1bf-11e6-92ce-add269a802a3.jpg)

**Comment by designker** [comment]
This will go away in 2.0
