### ISSUE TITLE
New ornament items since the last time

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#214]
List of items in my own inventory to follow, but also 'every new Dawning exotic ornament or SRL ornament or Trials flawless' ornamented item.

**Comment by floatingatoll** [comment]
Just from my own inventory:

2 ornament slots:

Speeder Gloves, Speeder Suit, Speeder Boots

1 ornament slot:

Lion's Vigil Strides

**Comment by floatingatoll** [comment]
Of particular interest is that the 3 weapons Bad Juju, MIDA, and Khvostov are bugged in 3 different ways, assuming you have both ornament slots unlocked.

**Comment by ArtistWolf** [comment]
Adding to the issues with Ornaments:

The following weapons do not show ornament slots for me:
• The Last Word
• Thorn
• Red Death
• Black Spindle.

Bad Juju shows two green circles around the ornament slots.

Khvostov has a green circle around the Last Warmind ornament. The Bureau is all blue, so I'm hoping I have that one installed.

**Comment by designker** [comment]
Not going to fix for D1
