### ISSUE TITLE
Yellow triangle isn't dimmed when Transfer is

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#216]

**Comment by floatingatoll** [comment]
![img_5470](https://cloud.githubusercontent.com/assets/92684/24837441/22204ea8-1ce9-11e7-9ea8-d89ecd65a8e5.PNG)

**Comment by designker** [comment]
Not a bug. I did this intentionally to make it clear which is the active character.

**Comment by floatingatoll** [comment]
Drat.
