### ISSUE TITLE
Vertical spacing between raid diamonds and baseline of text label varies across raids

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#218]
![file apr 23 11 33 55](https://cloud.githubusercontent.com/assets/92684/25316283/fb56823e-2818-11e7-92a9-3d0b783aa687.png)

**Comment by RedHotTrouble** [comment]
This is how this view is showing for me in Build 849.

Screenshot:
![img_2852](https://user-images.githubusercontent.com/14222975/26865156-b4ca46d4-4b18-11e7-9b98-03139dfd341c.PNG)

@floatingatoll, does this look to you like it's been fixed? I honestly can't tell if the vertical spacing is off...? 🤔 Maybe my eyes are too tired to tell the difference *squinting eyes* lol
