### ISSUE TITLE
Equipping item with detail window open updates some parts of detail window but not others

### ISSUE THREAD

**Issue by cowgod** [designker/ishtar-commander-bugs#22]
This may be an edge case that's not worth fixing, but I figured I'd log it anyway.

If my wi-fi connection or the Bungie API is slow, I can submit a request in the app to equip an item, and then long-press the currently equipped item to bring up its detail window. When IC finishes equipping the item, the detail window is updated to reflect the new item, but the Int/Disc/Str stats, perks, and their descriptive text still pertain to the old item.

1. Equip Glasshouse helmet

2. Tap Spektar Helmet and select to equip on Titan

3. Long-press equipped Glasshouse helmet to bring up popup
![img_1039](https://cloud.githubusercontent.com/assets/523086/15507740/cbb86856-219a-11e6-94f4-9eb08d9fe8ba.PNG)

4. When IC finishes equipping Spektar helmet, most of the detail window updates, but the the Int/Disc/Str stats, perks, and their descriptive text still refers to Glasshouse
![img_1036](https://cloud.githubusercontent.com/assets/523086/15507585/3a2fba56-219a-11e6-9150-4cde11062175.PNG)

If I bring up the detail for an equipped item and then equip a new item in-game, then wait for IC to auto-refresh, the bug doesn't occur. In that case, the detail window continues showing the old item, though in the dimmed background I can see the new item is now in the equipped slot.

![img_1038](https://cloud.githubusercontent.com/assets/523086/15507859/30ff8f32-219b-11e6-95b6-5e0ca1477a80.PNG)

**Comment by designker** [comment]
I won't be fixing this.
