### ISSUE TITLE
Popup "currently equipped" border isn't taken into account when iOS topbar active

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#222]
The other items display correctly a slight distance from the topbar, but the 'currently equipped' border isn't being taken into account and ends up being cut in half by it.

**Comment by floatingatoll** [comment]
![file apr 23 12 01 32](https://cloud.githubusercontent.com/assets/92684/25316477/bd3074b6-281c-11e7-8e7d-8f2a190db6eb.png)

**Comment by designker** [comment]
Considering how many of Apple's own apps break under these conditions I don't feel too bad

**Comment by floatingatoll** [comment]
Yeah, you’re doing swimmingly, I saw the popup recenter and was all “oooo”

**Comment by designker** [comment]
This should be fixed now

**Comment by floatingatoll** [comment]
![img_5849](https://cloud.githubusercontent.com/assets/92684/26035564/6069d8ae-3883-11e7-9c5d-4296948be216.PNG)

Build 827

**Comment by RedHotTrouble** [comment]
Can't replicate this issue on iPhone 7 with the latest Build 849.

@floatingatoll, is this still an issue for you? If not, is it okay to close it?

Screenshot:
![img_2850](https://user-images.githubusercontent.com/14222975/26864837-633d044c-4b17-11e7-850b-c7990bf2db10.PNG)
