### ISSUE TITLE
combine all the expert user preferences

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#223]
Everyone who wants any of [ Quest Spoilers, Hidden Stats, Armor Grades ] on probably wants all of them on, or doesn't mind that they're all on, anyways. Combining them into one preference would free up a chunk of space for those users.

**Comment by floatingatoll** [comment]
I could be persuaded just to merge [ Hidden Stats, Armor Grades ] instead, but there's clearly a chance to have one less preference somehow.

**Comment by cowgod** [comment]
I like this idea. I think Quest Spoilers should remain its own checkmark -- wanting or not wanting spoilers doesn't really equate to being a power user the way the other ones do. But I think Light Level, Hidden Stats, and Armor Grades make sense to combine into a single option. It could be called "Power User Mode" or maybe just "Advanced View" or "Advanced Stats".

**Comment by designker** [comment]
Not a bug. Redesign of settings will cover this though
