### ISSUE TITLE
Exotic Class Item text glitch

### ISSUE THREAD

**Issue by Lothaer** [designker/ishtar-commander-bugs#228]
When Harvesting/Gathering Engrams the tooltips for Chaon Cloak (FWC Exotic) and Stormcaller Bond (Warlock Exotic) tooltips glitch and duplicate evertime you start harvesting/gathering engrams.

Samsung Galaxy Note 4
Android 6.0.1
Ishtar Commander Build: 842

Please see below links for evidence.

http://i60.photobucket.com/albums/h10/lothaer/Mobile%20Uploads/Screenshot_2017-05-24-01-46-16_zpszbeda4tv.png

https://youtu.be/SAgix0LYO8E

**Comment by designker** [comment]
Fixed
