### ISSUE TITLE
Stat tiers scale with character level, Ishtar doesn't reflect this

### ISSUE THREAD

**Issue by cowgod** [designker/ishtar-commander-bugs#235]
Stat tiers are not always fixed at 60 points per tier -- this only applies at level 40. At lower levels, it takes fewer stat points to reach the next tier. My character is currently level 20, and with 66 discipline stat points, Ishtar shows it as tier 1 discipline, but in-game it is tier 3.
![img_1315](https://user-images.githubusercontent.com/523086/27012878-1f8089a2-4ea7-11e7-892f-e41adc0ca3b8.JPG)
![img_2293](https://user-images.githubusercontent.com/523086/27012879-1fe779aa-4ea7-11e7-8a6c-cbfe215ae77e.PNG)

**Comment by floatingatoll** [comment]
Is this a game-breaking issue for you that makes it difficult to level up
your character properly? (Serious request.)

**Comment by designker** [comment]
Lets keep the snark to Slack where it is easier to joke around. I will close these as I sort of know what is going on and don't want to spend the time fixing them as the system changes or goes away for D2.

**Comment by floatingatoll** [comment]
No, not snark, I didn't mean to be snark.

I couldn't think of a way this would break leveling up *but* if it was
causing problems with max light or something, then there would be a serious
issue. I'm sorry, no harm intended.
