### ISSUE TITLE
Clock skew causes Ishtar to wedge on 22 'bad token' error from Bungie.net

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#238]
Setting the clock forward a month (or 16 days), refreshing Ishtar, and then setting it back to correct time results in Ishtar attempting to use a bad token *eventually*, even after a force quit.

Initially, everything is fine, even if you set the clock back; it continues refreshing as normal for the next few seconds at least. (I didn't test, but I assume it's until one of the token-derived intervals ticks over.)

Bungie returns 22 `WebAuthModuleAsyncFailed` when an invalid token is provided. Not sure if it's an access or refresh token that triggers this.

After a force quit, only one single HTTP request is sent by Ishtar. The JSON response is shown below, as well as the curl command to reproduce the issue:

```
$ curl -D - -v -H 'X-API-Key: VALID_API_KEY_HERE' -H 'Authorization: Bearer BAD_TOKEN_HERE' 'https://www.bungie.net/d1/Platform/Destiny/2/Account/4611686018442199406/Summary/?lc=en'

HTTP/1.1 200 OK
...

{"ErrorCode":22,"ThrottleSeconds":0,"ErrorStatus":"WebAuthModuleAsyncFailed","Message":"We've encountered an error, please try again later.","MessageData":{}}
```

**Comment by floatingatoll** [comment]
You asked on Slack if the topbar appears 10 seconds after dismissing the error message; it does not (verified also by lothaer), nor do any further network requests occur. The fritz animation scroller continues to scroll and the pair of background concentric circles continue to dance.

**Comment by floatingatoll** [comment]
I am working on capturing the long-form of "leave Ishtar open for 60 minutes and record all network requests", but it may take some time.

**Comment by designker** [comment]
Fixed
