### ISSUE TITLE
When moving mod to vault, got JsonDeserializationError

### ISSUE THREAD

**Issue by cowgod** [designker/ishtar-commander-bugs#247]
I tried to move the blue mod in the screenshot to the vault. Got the pictured error: JsonDeserializationError.

![image](https://user-images.githubusercontent.com/523086/30930335-6e383080-a38f-11e7-925d-1685715740de.png)

**Comment by floatingatoll** [comment]
I get this same error on (I don't everything to test with here):

Scout Report: Io
Fireteam Medallion
Nessus Token

**Comment by floatingatoll** [comment]
Purple mods
Shaders

All attempting to transfer from inventory to vault.

**Comment by alexxnz** [comment]
Not exactly the same, but also get a VendorNotFound error when trying to equip emotes and emblems to other characters.
