### ISSUE TITLE
Vault emblem isn’t full width on iPad mini

### ISSUE THREAD

**Issue by cowgod** [designker/ishtar-commander-bugs#249]
Maybe it’s intentional but it seemed worth logging just in case. The black emblem for the vault doesn’t stretch the full width of the vault on an iPad mini 2 retina.

![1bfc5e0d-c85a-464c-aa5b-85b8d8c1a941](https://user-images.githubusercontent.com/523086/30939148-82bcc654-a3aa-11e7-82cb-8e0d1800035c.jpeg)

**Comment by designker** [comment]
Fixed
