### ISSUE TITLE
"Equip on..." buttons shouldn't be shown if item can't be transferred

### ISSUE THREAD

**Issue by cowgod** [designker/ishtar-commander-bugs#253]
The exotic power weapon, Legend of Acrius, can't be transferred to other characters (at least in the initial state that it drops at, before you complete the quest). Ishtar correctly hides the "Send to..." buttons on its transfer window, but it still shows the "Equip on..." buttons. Tapping the button for the character that's currently holding the weapon completes successfully, but tapping one corresponding to one of the other two characters results in an error message.

![img_2820](https://user-images.githubusercontent.com/523086/30997304-e4bf8784-a494-11e7-9ce8-e0f824eb1c87.PNG)

![img_2821](https://user-images.githubusercontent.com/523086/30997311-e90760be-a494-11e7-92b2-1692a7421f1b.PNG)

**Comment by designker** [comment]
fixed
