### ISSUE TITLE
Max glimmer shows as 99999+ in-game, ishtar shows 100000

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#255]

**Comment by alexxnz** [comment]
Although, in case it's not already known, game does show 100000 when hovering over the glimmer count

**Comment by RedHotTrouble** [comment]
Btw, I don't believe this is a "bug." Max glimmer = "99999+" = 100000. In-game, when you hover over it, game also shows you 100000. So that's essentially the correct value when you're maxed out.

**Comment by designker** [comment]
Not going to fix
