### ISSUE TITLE
Emblems Show "Equip On" All Characters

### ISSUE THREAD

**Issue by RedHotTrouble** [designker/ishtar-commander-bugs#258]
In Destiny 2, emblems are no longer transferable via D1's standard Vault system; but rather through D2's new Vault Collections. Therefore, if a character doesn't already have its own copy of a selected emote in its its inventory, the emblem can't really be equipped to other characters.

Showing "Equip On" all three characters feels a bit misleading, suggesting that the action will work across all characters. But the chance of that working is very small...?

**Comment by floatingatoll** [comment]
Perhaps related to #253

**Comment by alexxnz** [comment]
Fixed in beta 105
