### ISSUE TITLE
Ishtar is always purple in Recent Apps on Android

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#259]
"I have a Google Pixel with Android 8.", says @lostyBO.

https://developer.android.com/training/material/theme.html#ColorPalette

**Comment by floatingatoll** [comment]
![screenshot_20171002-221235](https://user-images.githubusercontent.com/92684/31098689-5333a746-a778-11e7-8a34-4446e975b6d0.png)

**Comment by designker** [comment]
fixed
