### ISSUE TITLE
Green postmaster icon doesn't go away after emptying postmaster

### ISSUE THREAD

**Issue by cowgod** [designker/ishtar-commander-bugs#26]
I accumulated a bunch of items in my postmaster and IC correctly showed the green icon in my character's nameplate showing they're there. However, after emptying the postmaster in game, the green icon remains, even after a refresh. Tapping the nameplate shows the postmaster as empty, so Ishtar definitely has the latest data.

![image](https://cloud.githubusercontent.com/assets/523086/15690047/aba42e3c-274f-11e6-9dd1-047b3543e599.png)

**Comment by designker** [comment]
fixed
