### ISSUE TITLE
Missing language fonts (Android)

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#263]
I believe I'm missing the fonts needed to render the Asian languages. Below is a screenshot of the language selector. They were working in one of the previous betas.
No text appears when I select one of those languages.

Beta 89 on Android 7.1.2, Nexus 5X

![screenshot_20171003-201114](https://user-images.githubusercontent.com/16849366/31154913-55715e08-a878-11e7-9d1f-594aaab3dd45.png)

**Comment by alexxnz** [comment]
The reported issue has been fixed in beta 95 on Android. However, I also just noticed that Russian does not appear UNLESS using one of the Asian languages.
Russian is still selectable even though it does not appear as an option (it's invisible)

**Comment by designker** [comment]
Fixed
