### ISSUE TITLE
Items change despite already maxed

### ISSUE THREAD

**Issue by netniV** [designker/ishtar-commander-bugs#264]
For example, I was already maxed in power, so I changed my kinetic weapon.   Upon hitting max power, it correctly changed my kinetic weapon.  What I didn't notice at first was that it had also changed my power weapon despite the existing power weapon already being of the same level.

Attached zip file contains a video demonstrating this.

[Power weapon changes, despite being maxed already .zip](https://github.com/designker/ishtar-commander-bugs/files/1356277/Power.weapon.changes.despite.being.maxed.already.zip)

**Comment by designker** [comment]
This should be fixed now. Please retest
