### ISSUE TITLE
auras (e.g. heroic nightfall) show qty.2 on one of three characters

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#265]
both ishtar and official companion show qty.2, but just for one of the three characters.

![image uploaded from ios](https://user-images.githubusercontent.com/92684/31247929-f6ec7426-a9c6-11e7-8432-042e6c727e36.png)

![image uploaded from ios 4](https://user-images.githubusercontent.com/92684/31247967-148debe0-a9c7-11e7-9128-6859c5a24924.jpg)

**Comment by designker** [comment]
fixed
