### ISSUE TITLE
Double tap mod, tries to equip

### ISSUE THREAD

**Issue by netniV** [designker/ishtar-commander-bugs#266]
When you try to move mod items from your vault using double tap, you receive a worrying not found error. I think this is because it’s trying to equip the mod in your current character and obviously can’t find it as it’s in shared inventory space. 

![Image](https://i.imgur.com/gGDF4R1.jpg)

**Comment by floatingatoll** [comment]
This also occurs with Arcology Tokens, shaders, and ornaments.

**Comment by netniV** [comment]
Is this still an active problem?  Just wondering as it's in my list of open issues.

**Comment by floatingatoll** [comment]
Nigel says he fixed it in the (354) release notes
