### ISSUE TITLE
Adaptive Icon on Android

### ISSUE THREAD

**Issue by cassidyjames** [designker/ishtar-commander-bugs#268]
The new app icon looks great and seems like it would work well as an adaptive icon. You'd have to split it into two layers and then it would get masked to the right shape depending on your launcher/OEM/whatever 

See https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html for details.

This is a new feature in Android 8.0.

**Comment by cassidyjames** [comment]
Here's what it looks like in context:￼

**Comment by designker** [comment]
fixed
