### ISSUE TITLE
Back button disables certain actions (Android)

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#269]
Noticed a few things in the new beta (105)

It seems using the system Back button to escape certain screens/popups will disable those actions.
If I tap and hold on an item to view its stats, and press the Back button, I can no longer inspect any other items using tap and hold. However Gear Transfer will still appear on tap.

Settings section is also affected by this. Backing out of the Settings screen with the Back button will prevent you from accessing it again, at least until you relaunch the app. Tapping to escape Settings screen is unaffected.

**Comment by designker** [comment]
fixed
