### ISSUE TITLE
Transmats don’t stack until refresh

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#270]
After transferring to vault. Pull to refresh repairs it.

**Comment by floatingatoll** [comment]
![71e8979d-3725-4157-b840-225936f71836](https://user-images.githubusercontent.com/92684/31771055-77a4d5d6-b48f-11e7-89b4-7d52be6bf885.png)

**Comment by designker** [comment]
This is fixed now
