### ISSUE TITLE
Pull to refresh sticks open if held down long enough

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#273]
If I pull to refresh and hold it until the refresh is Done, the refresh icon sticks at the top until I scroll away.

**Comment by floatingatoll** [comment]
1121 fixes

**Comment by floatingatoll** [comment]
occurs much more rarely since, most recently in (138), iphone and ipad, video on slack

**Comment by designker** [comment]
Cannot reproduce
