### ISSUE TITLE
Titan mark doesn’t show “Requires Titan Class” in-game

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#274]
It’s already type Titan Mark, so that’s probably why.

**Comment by floatingatoll** [comment]
My Titan helmet doesn’t either.

**Comment by designker** [comment]
Sounds like a bungie bug. I need some screenshots

**Comment by floatingatoll** [comment]
Ishtar:

![photo_ - 2 1](https://user-images.githubusercontent.com/92684/31857977-5cbb9174-b6a1-11e7-8a70-6ea907a5ea7b.png)
![photo_ - 1 3](https://user-images.githubusercontent.com/92684/31857978-5cd12a2a-b6a1-11e7-94b6-3c1f99464cd6.png)

Destiny:

![destiny 2_20171021203948](https://user-images.githubusercontent.com/92684/31857989-6cefba3e-b6a1-11e7-969e-65691a53e304.jpg)
![destiny 2_20171021203946](https://user-images.githubusercontent.com/92684/31857991-706736b0-b6a1-11e7-9456-27c8f7cf3d20.jpg)

**Comment by designker** [comment]
This as with Ishtar for D1 is intentional
