### ISSUE TITLE
Mod text is missing blue hue for e.g. “Power weapon”

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#277]
In game, my cloak mod says “equipped Power weapon”, but the “Power weapon” text is a nice shade of blue.

Ishtar does not show this coloration.

**Comment by floatingatoll** [comment]
Also the “Void” in “Void melee abilities”.

**Comment by floatingatoll** [comment]
It appears to be specifically NOT present on legendary weapon mods, which present with italics rather than normal text, because ???.

**Comment by designker** [comment]
There is no way to fix any of these due to the way bungie only provide plain text descriptions
