### ISSUE TITLE
Mod icon on armor in item stats is different from in-game

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#279]
In game, the armor mod icons in the stats view are black background and lack the useful background color and bottom-left corner hint about weapon type.

In Ishtar, the mods in the Stats view are shown matching the in-game Detail view instead, with blue/purple background and weapon slot overlay in the lower left.

This may or may not be a bug.

**Comment by alexxnz** [comment]
for reference, this is what the stats view looks like in-game

![stats view - exotic](https://user-images.githubusercontent.com/16849366/32303946-31b88ee2-bf42-11e7-8623-241b65b08459.png)

**Comment by designker** [comment]
Bungie don't provide that icon
