### ISSUE TITLE
Armor grading tooltip doesn't singularize "stat points" string

### ISSUE THREAD

**Issue by cowgod** [designker/ishtar-commander-bugs#28]
When viewing an armor piece's detail page and tapping on the armor grading bars to bring up the tooltip, if the armor only has one more stat point to gain, the tooltip says "Infuse to 335 to gain 1 stat points." The final "s" should be removed when there's only one point to gain.

![image](https://cloud.githubusercontent.com/assets/523086/15919562/8f3c6eb6-2de0-11e6-8795-6ffb4ad22dbd.png)

**Comment by designker** [comment]
Not going to fix
