### ISSUE TITLE
Stats perk list has different lower boundaries than in-game

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#285]
The lower boundaries (inner and outer) for the perk list on the Stats page of an item has a different set of lower boundary distances than in-game.

**Comment by floatingatoll** [comment]
In-game: ![78a5952a-4674-4491-9e5d-76ebc4703021](https://user-images.githubusercontent.com/92684/31851298-d893e312-b617-11e7-953e-494f31373b86.jpeg)

Ishtar: ![e2510b4f-7cf1-4206-8c21-449d5469fd03](https://user-images.githubusercontent.com/92684/31851301-e3a7a3ce-b617-11e7-965a-bb270a33e197.jpeg)

**Comment by floatingatoll** [comment]
![21436ccb-db75-4e8f-9b47-079ab4ff4e47](https://user-images.githubusercontent.com/92684/31851629-90a42c4a-b61e-11e7-90fc-55388bb7b4e9.png)

**Comment by designker** [comment]
Not going to fix
