### ISSUE TITLE
Shader popup isn’t styled to match in game

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#286]
The heading is black rather than gray and the description isn’t italic.

![2aff3220-6bd8-4133-9716-b90b1a23f77e](https://user-images.githubusercontent.com/92684/31851330-940bc9fc-b618-11e7-9e27-11ed11812961.png)

**Comment by floatingatoll** [comment]
Also in game it doesn’t have a thin gray bar at the top.

**Comment by floatingatoll** [comment]
This same issue also applies to the equipped-gun-mod long-press popups.

**Comment by alexxnz** [comment]
didn't see this earlier, but is very similar to issue #314 which has in-game reference

**Comment by designker** [comment]
I am using #314 to track this, even though this was first
