### ISSUE TITLE
Detailed item view is inconsistent when in Postmaster section

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#29]
I noticed some inconsistencies with the way the weapon/armor pop-ups are displayed from the postmaster section, when compared to the rest of the app. Not a huge deal, but I wanted to make sure you were aware.
The following screenshots are all from build 523.

The first 2 screens are from an iPad 3rd gen. In the postmaster, the popup is huge compared to what normally shows in the weapons section.
![oversized](https://cloud.githubusercontent.com/assets/16849366/16320268/ebb9f7b4-3964-11e6-9d77-8e87d86a7c04.PNG)
![normal](https://cloud.githubusercontent.com/assets/16849366/16320273/eea1fb7a-3964-11e6-81b9-8bcf63905f82.PNG)

I noticed some issues in Android as well. First, it seems the pop-up is cut off at the top when viewing postmaster items in landscape.
![1](https://cloud.githubusercontent.com/assets/16849366/16320312/2521d0d0-3965-11e6-82d2-a7ec3c62ba9c.png)

When in portrait, postmaster items have a small margin at the top:
![2](https://cloud.githubusercontent.com/assets/16849366/16320390/6a567296-3965-11e6-8339-b39af6203112.png)

However in the weapons tab, the pop-ups sit flush at the top of the screen:
![3](https://cloud.githubusercontent.com/assets/16849366/16320409/82fa6690-3965-11e6-93c9-8a4b01681a9d.png)

There are exceptions, of course:
![4](https://cloud.githubusercontent.com/assets/16849366/16320415/8b0ab81c-3965-11e6-87c6-5ab7f6291edd.png)

**Comment by designker** [comment]
fixed
