### ISSUE TITLE
Description text is a different color than in-game, I think

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#291]
In-game, if you look at a scout report, all the text is the same color in the lower section. But in Ishtar, some of that text is a brighter white than the rest.

**Comment by floatingatoll** [comment]
Yeah, if you go to any exotic weapon, in-game shows the same color text for all perk descriptions, but Ishtar shows different colors between the exotic perk and the non-exotic perks.

**Comment by designker** [comment]
Fixed
