### ISSUE TITLE
Vertical gap differs when a gun has multiple perks

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#298]
![2b079c12-d702-4fb8-9efc-859aae95f1f9](https://user-images.githubusercontent.com/92684/31851611-295e47c8-b61e-11e7-8d2f-45812a248378.png)
![2a54b827-7287-4514-b5b1-f8f8705c726e](https://user-images.githubusercontent.com/92684/31851612-297a29e8-b61e-11e7-86b9-e491f1be7bd3.jpeg)

The vertical spacing between the two final perks shown below differs between ingame and Ishtar.

**Comment by designker** [comment]
fixed
