### ISSUE TITLE
Grid mismatch on gun with single row of perks

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#299]
The lower gridline in Ishtar isn’t shown in game.

![a0462bbc-197c-4b6e-8254-105b69da4f83](https://user-images.githubusercontent.com/92684/31851641-d57664d2-b61e-11e7-91d1-998d2959af96.jpeg)
![7e59c2a6-49a9-4932-ba93-e2cec592b37c](https://user-images.githubusercontent.com/92684/31851642-d595b8be-b61e-11e7-840e-51a224c06802.jpeg)

**Comment by designker** [comment]
fixed
