### ISSUE TITLE
Ishtar currently does not remember column position on device rotation

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#30]
In portrait view, the app currently remembers what column you were last on when exiting and restarting the app.
However, when rotating from portrait to landscape, and then back to portrait, the app defaults to showing the first column.
Is it possible to have the app return to the last viewed column when switching orientation?

**Comment by designker** [comment]
This turned out to be quite hard. Not going to fix, but I have a note to look at this as a future feature
