### ISSUE TITLE
Exotic ornament misplacements

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#300]
![image uploaded from ios 1](https://user-images.githubusercontent.com/92684/31851756-fdca1b20-b620-11e7-8078-5232f9161af0.png)

**Comment by floatingatoll** [comment]
![image uploaded from ios 2](https://user-images.githubusercontent.com/92684/31855449-6ca68dc8-b660-11e7-94ab-028f884459ac.png)

**Comment by alexxnz** [comment]
Same issue occurs on transmat effects for ships.

**Comment by alexxnz** [comment]
fixed
