### ISSUE TITLE
Android Adaptive Icon is backgroundless

### ISSUE THREAD

**Issue by cassidyjames** [designker/ishtar-commander-bugs#306]
Adaptive Icons on Android consist of a background and foreground layer. The OS uses this (and in future versions, will likely more heavily use this) not only for masking, but for some subtle animations and effects.

One place it's used right now is when dragging an icon on the home screen: the foreground layer slides around with the inertia of moving the icon, giving a sense of depth.

It appears Ishtar Commander (as of #268) only provides a branded foreground layer, meaning **the default unbranded background layer ends up peeking through in some animations.**

Instead, it would be better to separate the icon into two distinct layers, ensuring the background (white gradient, texture, and maybe the light colored circles) fills the entire size of the image, with a separate foreground layer (dark foreground strokes) on top.

If I had access to full quality original assets, I could try and put something together.

I'll upload a screencast of the animation shortly.

**Comment by cassidyjames** [comment]
Screencast

**Comment by designker** [comment]
Pretty sure this is fixed now
