### ISSUE TITLE
Int/Disc/Str tier pop-up duration has been greatly reduced

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#31]
In the past couple of builds, tapping for int/disc/str tier details displays the pop-up for only 1 second before disappearing again.

As it is now, it is near impossible to get any information out of that pop-up without tapping and holding.

**Comment by designker** [comment]
Fixed in next build

**Comment by alexxnz** [comment]
I believe this was fixed, but it is currently happening again in Build 596

**Comment by designker** [comment]
fixed
