### ISSUE TITLE
Switching languages occasionally does not fully switch over

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#313]
Not sure how exactly to replicate, but I've seen it a few times already just switching languages looking for bugs.

When switching languages, occasionally Ishtar will not fully refresh to the selected language, so you end up getting some text in the previous language, and other text in the selected language.
It seems most (if not all) of the text that is manually localized switches over, but anything pulled from the API still displays in the previous language.

Beta 137

**Comment by designker** [comment]
I have not seen this issue happen recently
