### ISSUE TITLE
Equipped mods/shaders pop-up UI doesn't match in-game

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#314]
In-game UI shows equipped mods/shaders on hover with a pop-up matching the item's rarity color. In Ishtar's details view, the pop-up is always black. Same applies to equipped transmat effects for ships.

In-game UI shown below

![equipped armor mods - legendary](https://user-images.githubusercontent.com/16849366/32295300-3b71e73a-bf1f-11e7-9ce0-3457a63151fd.png)

![equipped mod details - rare](https://user-images.githubusercontent.com/16849366/32295304-41e125a4-bf1f-11e7-8d55-a6bcd5d3cc69.png)

![equipped shader details - uncommon](https://user-images.githubusercontent.com/16849366/32295308-45930af0-bf1f-11e7-9b0c-9eaaa9a46591.png)

![equipped transmat - rare](https://user-images.githubusercontent.com/16849366/32295352-6c3a78aa-bf1f-11e7-8110-0d2167e27502.png)

**Comment by designker** [comment]
This is probably not 100% fixed so new bugs with screenshots should be raised. But the latest build addresses the issues in this specific report
