### ISSUE TITLE
Mod details pop-up doesn't match in-game UI

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#316]
Long pressing mods in the inventory section show blue colored mod icons next to the item's description. In-game, the icon is colorless (in-game screenshot below)

Also, legendary mods don't show power level in-app [ see issue #287 ]

![mod details - legendary](https://user-images.githubusercontent.com/16849366/32295696-732b14b6-bf20-11e7-95b5-562966b684da.png)

**Comment by designker** [comment]
This is fixed
