### ISSUE TITLE
Pop-ups overlap with system taskbar

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#317]
In landscape view, pop-ups can overlap with the system's taskbar at the top. 
I'm only able to replicate this on an Android phone (Nexus 5X), so can't say if something similar happens on iOS.

![screenshot_20171101-153533](https://user-images.githubusercontent.com/16849366/32300997-6419bbc8-bf32-11e7-971f-0941d42d9298.png)

**Comment by floatingatoll** [comment]
iOS 11.latestdevbeta:
![09beaa49-1a7b-4660-9b4e-2e64abc08900](https://user-images.githubusercontent.com/92684/32302271-0d3f4646-bf1f-11e7-9a0b-b9d7cf384f85.png)

**Comment by floatingatoll** [comment]
Things are very different now, seems fixed
