### ISSUE TITLE
Legacy login still enabled after unchecking legacy option

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#32]
I attempted logging in to the app, enabled legacy login, tapped on PlayStation logo to login, then backed out to initial screen, disabled legacy login, and when tapped the PS logo again, it brought me back to the legacy login screen instead of the web view. 

Also, Android OS back button closes the app on legacy login screen, instead of backing up to the initial screen.

**Comment by designker** [comment]
fixed
