### ISSUE TITLE
Ishtar should not allow transfer of Lost Items

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#323]
As of Beta 138, Ishtar will let you move certain items that are in the Postmaster.

This doesn't happen with engrams, as those don't provide a Transfer option, but I was able to do this with an EDZ token. Selecting Transfer on the token, that was in my Postmaster, gave me the option to transfer to my alt characters and the vault.
Ishtar will actually transfer the items in-app without error (although nothing occurs in-game). After auto-refresh, the item will appear back in the original character's Lost Items section.

Double-tap should also be disabled on Lost Items.

**Comment by alexxnz** [comment]
in beta 140, postmaster items no longer have transfer option, but still attempt move on double-tap

**Comment by designker** [comment]
fixed
