### ISSUE TITLE
Style for stats view is different for items in Postmaster

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#325]
Specifically, the intrinsic perk block is normally shaded lighter than the rest of the pop-up in stats view. However, for items in the Postmaster, the intrinsic perk block is shaded the same color as the rest of the pop-up. (Beta 140)

See #324 for how this looks in-app

**Comment by designker** [comment]
Dupe of #324 and waiting for a bungie fix
