### ISSUE TITLE
Gear Transfer Layout needs margin for longer titles

### ISSUE THREAD

**Issue by netniV** [designker/ishtar-commander-bugs#326]
Some mod titles appear to wrap correctly on the Gear Transfer screen such as the Kinetic Counterbalance Mod, where others are bumping right to the edge of the "SEND TO" column, such as Kinetic Munition Loader.

**Comment by netniV** [comment]
Correct layout:
![image](https://user-images.githubusercontent.com/9052188/32830186-4f9ea996-c9ec-11e7-82f9-2eedf2152b30.png)

**Comment by netniV** [comment]
Incorrect layout:
![image](https://user-images.githubusercontent.com/9052188/32830207-5b12dd4c-c9ec-11e7-94ad-fbe443a8c537.png)

**Comment by designker** [comment]
Fixed this ages ago
