### ISSUE TITLE
Android back button does not back out of legacy logon screen

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#33]
Currently, while on the legacy login screen, pressing the the Android OS Back button will exit the app.
I expected it to take me back to the main logon window where I select to authenticate with PlayStation or Xbox credentials.
The in-app Back button works for this purpose, but I'm not sure it's need on Android since all devices have the native back button for this functionality.

**Comment by designker** [comment]
Won't fix for now
