### ISSUE TITLE
Canceling a side-swipe doesn’t reset the state of the STATS/DETAILS buttons

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#336]
When swiping left from a gift schematic to a ghost and then canceling the swipe before it snaps over to the ghost. Video on slack (172)

**Comment by designker** [comment]
That is as intended. Those buttons don't ever reset

**Comment by floatingatoll** [comment]
I meant visible/hidden state - not which one is selected - sorry for the confusion
