### ISSUE TITLE
DEFAULT ORNAMENT header is taller in-app than in-game

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#338]
Ishtar leaves a blank empty row for the "item type" subtitle but in-game it's shortened without it.

**Comment by floatingatoll** [comment]
Shortened in-game header:

![fullsizeoutput_23ae](https://user-images.githubusercontent.com/92684/34463264-5e9e125a-ee0a-11e7-9020-d5f6732efc94.jpeg)

**Comment by floatingatoll** [comment]
Unshortened in-game header:

![equipped armor mods - legendary](https://user-images.githubusercontent.com/16849366/32295300-3b71e73a-bf1f-11e7-9ce0-3457a63151fd.png)

**Comment by designker** [comment]
Fixed in the next build
