### ISSUE TITLE
Requires Level 22 is vertically-offset incorrectly

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#348]
![image](https://user-images.githubusercontent.com/92684/37848464-7a984de6-2e91-11e8-95a8-955ae357d721.png)

**Comment by alexxnz** [comment]
For reference, I've attached an in-game screenshot

![destiny 2_20180511015920](https://user-images.githubusercontent.com/16849366/39909450-e04228a6-54c0-11e8-98c5-486465d94555.png)
