### ISSUE TITLE
SSL error is displayed weirdly

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#349]
This screenshot is from my iPhone when I was trying to set up interception.

**Comment by floatingatoll** [comment]
![147ece95-3628-42dc-b7f5-12c51ee91982](https://user-images.githubusercontent.com/92684/38013600-91650f14-321a-11e8-8d72-5fd2e560b9cd.png)

**Comment by designker** [comment]
Not going to fix
