### ISSUE TITLE
Emblems fade in with jade rabbit no matter which emblem

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#355]
In every fade-in in this video (249), you can see Jade Rabbit eyes in the fade-in animation, even for non-Jade emblems.

https://www.dropbox.com/s/k8ok0jdw5gmg6ou/ScreenRecording_06-02-2018%2010-43-41.MP4?dl=0

**Comment by designker** [comment]
Fixed
