### ISSUE TITLE
Emblem corner yellow triangle is offset a couple pixels from edges

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#356]
![a2016a3e-789e-4c4b-868d-868e0d95a36e](https://user-images.githubusercontent.com/92684/40879366-9efc40d0-6653-11e8-9f18-af2439fdb5a2.jpeg)
![368f5b26-ce5d-409b-98bf-a237b76dae3c](https://user-images.githubusercontent.com/92684/40879367-9f14a83c-6653-11e8-8377-7b877e631ae2.jpeg)

**Comment by designker** [comment]
As intended
