### ISSUE TITLE
Armor class highlight is applied to cloak mod row

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#358]
Maybe because it’s the first row and there’s no armor class row? (249)

![bbcc1fa9-3064-4d24-97ba-cb46101564da](https://user-images.githubusercontent.com/92684/40879582-499be9e8-6657-11e8-8b9e-8d2ae14c8d86.jpeg)

For comparison, legs with the highlight:

![24a6127a-eec7-43b5-9dc6-9e16e5b49166](https://user-images.githubusercontent.com/92684/40879586-53b9d282-6657-11e8-94f1-fc01eb88a5a6.jpeg)

**Comment by designker** [comment]
Cannot reproduce
