### ISSUE TITLE
App loads into blank inventory screen

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#36]
This is related to issue #35. I was only able to replicate this on Android, but it seems after the crashes the app loads into a blank inventory screen (see below)
In this state I can swipe between pages, but the upper-left refresh button doesn't do anything. I can bring up the settings menu and can change values there normally, but until I either log out or do a full refresh, I can't use the app normally.
Even if I were to exit the app, swipe it out of the multitasking view, and perform a system force stop on the app, the next time I load the app, it would load in this blank state.
![screenshot_20160627-152325](https://cloud.githubusercontent.com/assets/16849366/16393238/ef90d044-3c7d-11e6-8556-2a2ef54c9f45.png)

Here are the steps I went through to replicate (assuming already logged out):

1. Select PSN login
2. Press back button while page loads
3. App crashes; dismiss Android crash notification
4. Load Ishtar
5. Select Xbox login
6. Press back button while page loads
7. App crashes; dismiss Android crash notification
8. Repeat ad nauseam 

At one point I was able to reproduce it by just switching from PSN -> Xbox -> PSN and then I got the blank screen, but right now, I'm having a hard time reproducing it. Maybe performing a force stop contributed to me not being able to reproduce consistently.
Prior to the force stop, I was able to get to this screen at least on 3 different occasions.

**Comment by designker** [comment]
Not going to fix
