### ISSUE TITLE
Masterwork counter baseline is offset vertically from text baseline

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#363]
The baseline of the text and the baseline counter are offset slightly in Ishtar.

**Comment by floatingatoll** [comment]
![40de440a-2c96-4359-8151-75f2307bc9b4](https://user-images.githubusercontent.com/92684/41139757-89a7b6de-6a9e-11e8-987d-fee93f11ccba.jpeg)

**Comment by designker** [comment]
Cannot reproduce
