### ISSUE TITLE
Flavor text baseline is off-center versus game on ghosts (maybe others?)

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#364]
Left Ishtar, right in-game

**Comment by floatingatoll** [comment]
![ddf1e33a-ca49-4adb-801e-02332a3f6aef](https://user-images.githubusercontent.com/92684/41139944-a57e6442-6a9f-11e8-931b-b62295c0a0aa.jpeg)

**Comment by designker** [comment]
Not going to fix
