### ISSUE TITLE
Transfer right edge line is offset from item grade vs. in-game isn’t

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#365]
Ishtar left, in-game right

**Comment by floatingatoll** [comment]
![168847fe-4ed2-4d5e-a7da-a84eb4be93a4](https://user-images.githubusercontent.com/92684/41140625-72a947c2-6aa3-11e8-8cf8-45d247bcb4de.jpeg)
![Uploading 62CF792E-98AC-44AD-9D21-DFA4C76CA188.jpeg…]()

**Comment by designker** [comment]
Fixed in next version
