### ISSUE TITLE
Challenge card missing Stats, Details buttons

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#366]
I only have a legendary one to test but presumably also the blue one too. In-game has a Details command and shows “Nightfall Modifiers”:

![09893d65-0cf2-4fcd-a5e1-5352014b95dd](https://user-images.githubusercontent.com/92684/41140784-383fdc08-6aa4-11e8-8173-fbdec7229741.jpeg)

**Comment by designker** [comment]
I won't fix this as it has been replaced by the newer card
