### ISSUE TITLE
Challenge card multiplier is %f in-game, %.1f In Ishtar

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#367]
Ishtar left, in-game right

**Comment by floatingatoll** [comment]
![a0a0a925-ebca-46b4-9255-ec2eeeaa7f16](https://user-images.githubusercontent.com/92684/41140842-8bcc36a0-6aa4-11e8-9307-20142f3b7988.jpeg)
![da2b07f8-2beb-4eec-a9e5-0ab928e783a7](https://user-images.githubusercontent.com/92684/41140843-8be64a04-6aa4-11e8-9659-723c2bd39d46.jpeg)

**Comment by floatingatoll** [comment]
(In-game also uses the 1x form on individual perks’ Multiplier Bonus.)

**Comment by designker** [comment]
Should be fixed in the next version

**Comment by floatingatoll** [comment]
Looks good
