### ISSUE TITLE
Mouseover item popups appears underneath when transfer dialog open

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#372]
"I thought it would either display in the front or not at all"

![image 1](https://user-images.githubusercontent.com/92684/44872653-fb641e00-ac4a-11e8-84e6-f3f6ee512474.png)

https://ishtar-commander.slack.com/archives/C0A8AT23Y/p1535654873000100 includes a mention of mouseover appearing while drag-and-drop, too:

![image 2](https://user-images.githubusercontent.com/92684/44873033-f81d6200-ac4b-11e8-99c9-93d8ddf5eb55.png)

**Comment by designker** [comment]
Fixed ages ago
