### ISSUE TITLE
Weapon/Armor icon in transfer dialog does nothing on tap

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#40]
I'm not sure if this was always like this, but when in the transfer dialog, the icon for whatever item you're about to transfer has a shimmer on it indicating that it can be interacted with. 
Tapping the icon currently does nothing, although holding will bring up the details pop-up. 

I imagine some folks would get confused by seeing the shimmering icon, then tapping on the icon, only to get nothing, not realizing they can tap and hold to see item details.

**Comment by designker** [comment]
Fixed this in the morning. It will be in tomorrows build.
