### ISSUE TITLE
After equipping an emblem, badge reverts to old emblem

### ISSUE THREAD

**Issue by cowgod** [designker/ishtar-commander-bugs#41]
When equipping an emblem from the Inventory page, Ishtar initially updates the display correctly -- the emblem at the top of the window changes to the new one, etc. But about 30 seconds later (presumably after auto-refresh completes), the emblem displayed in the badge at the top, and in the item transfer window, reverts to the old one. It appears that the emblem was equipped correctly in game and does not change back.

In the screenshots below, I had just switched my Titan FROM the Iron Banner emblem to a regular one. You can see in the Inventory window that the regular emblem is equipped, but the Iron Banner emblem is displayed at the top and in a transfer window.

![image](https://cloud.githubusercontent.com/assets/523086/16544359/5e5d8c5e-40d1-11e6-9bbc-9362faaa6e2b.png)
![image](https://cloud.githubusercontent.com/assets/523086/16544360/5e6ffe66-40d1-11e6-9c29-7dd971aced9e.png)

**Comment by designker** [comment]
Bungie send out of date data. That is a bungie bug.
