### ISSUE TITLE
Challenge of Elders sigil doesn't pick up target score

### ISSUE THREAD

**Issue by cowgod** [designker/ishtar-commander-bugs#43]
I completed CoE sigils on all three characters today, and two of them show completed in Ishtar, but one of them shows a zero for the target scores for High Score and Cumulative Score:

![img_1069](https://cloud.githubusercontent.com/assets/523086/16842388/50e248c0-49ab-11e6-9690-b00e3782de6b.jpg)

**Comment by floatingatoll** [comment]
Is the one that shows a zero score the one that isn't marked as completed on the left?

**Comment by cowgod** [comment]
@floatingatoll: Yes, that's the one that's selected for the popup.

**Comment by designker** [comment]
fixed
