### ISSUE TITLE
Accented characters show incorrectly (build 565)

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#45]
Before DB code update, est. build 530 or so:

![Before:](https://cloud.githubusercontent.com/assets/92684/16934739/1b0ff038-4d0e-11e6-9874-fa514a2725cd.png)

After DB code update, build 565

![After:](https://cloud.githubusercontent.com/assets/92684/16934740/2484a992-4d0e-11e6-905b-77d2ac316ffc.png)

**Comment by floatingatoll** [comment]
Build 565.

**Comment by floatingatoll** [comment]
Someone reported on Slack that Fang of Ir Yüt is IR YXFBT, so presumably xFB like xE4 above.

**Comment by designker** [comment]
Fixed in the next build

**Comment by floatingatoll** [comment]
This is still broken in build 573 for Häkke weapons.

**Comment by floatingatoll** [comment]
Verified fixed in 574

**Comment by alexxnz** [comment]
I'm unable to reopen this issue, but Fang of Ir Yût is still affected by this bug (build 574).
I can also confirm that Façade of the Hezen Lords is also broken (shows as FAXE7ADE OF THE HEZEN LORDS)
I presume there are other special characters that might be affected as well.

**Comment by alexxnz** [comment]
As far as I can verify, all seems well with build 575.
