### ISSUE TITLE
Vertical alignment mismatch between weapon type and rarity

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#46]
As of build 565 and a couple months prior, the weapon subheading "Pulse Rifle" is at a different vertical alignment than the text "Legendary 🔒". In actual Destiny, these two phrases share the same baseline. Note, however, that in actual Destiny the heading box is slightly taller, so the lower margin on the text "Legendary" is more correct.

![Misalignment](https://cloud.githubusercontent.com/assets/92684/16934818/0df03808-4d0f-11e6-8131-17bf4ea37947.png)

**Comment by designker** [comment]
Fixed in the next version

**Comment by floatingatoll** [comment]
Verified in 573, thanks!
