### ISSUE TITLE
Armsday package shows light level when Destiny does not.

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#47]
When inspecting the contents of an Armsday package with Ishtar, it shows a 280 banner on each weapon that isn't present in the Destiny actual UX.

![Ishtar](https://cloud.githubusercontent.com/assets/92684/16934877/895703f0-4d0f-11e6-80e9-a9dc17bd6efe.png)

![Actual](https://cloud.githubusercontent.com/assets/92684/16934879/8c80cae8-4d0f-11e6-8e27-4d0ad5cafb6d.png)

**Comment by floatingatoll** [comment]
Build 565.

**Comment by designker** [comment]
If you have light levels turned on this is the expected behaviour. By default this would indeed have them missing.
