### ISSUE TITLE
Transfer dialog is missing 'CURRENTLY EQUIPPED' boundary for equipped items

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#48]
When inspecting a currently equipped item, the white border and footnote is shown. However, the transfer dialog shows neither the whiteborder, nor the footnote, nor any other indication that it's currently equipped other than the blank area where 'Equip For' used to be.

Equipped in Detail:

![Detail](https://cloud.githubusercontent.com/assets/92684/16935010/6cf68d42-4d10-11e6-9a62-a89a80653253.png)

But not shown in Transfer:

![Transfer](https://cloud.githubusercontent.com/assets/92684/16935014/72dc6a1a-4d10-11e6-8598-dd299e91554e.png)

**Comment by floatingatoll** [comment]
Build 565.

**Comment by designker** [comment]
This is intentional
