### ISSUE TITLE
Loading spinners show, briefly, on every perk icon, every time.

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#49]
When viewing a weapon, either in Transfer or in Detail view, the perks show an animated spinner momentarily every time, even if I view the same details five or ten times in a row. It seems to speed up slightly after the first time, but there's still a half second or less of animated spinner before suddenly all the icons load in at once. (This may be intentional.)

**Comment by floatingatoll** [comment]
Build 565.

**Comment by designker** [comment]
Fixed in the next build

**Comment by floatingatoll** [comment]
Verified in 573, thanks!
