### ISSUE TITLE
Rotating from portrait to landscape (accidentally) loses place when returning to portrait

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#51]
Now that Ishtar supports landscape mode on the 6S, I am constantly losing my place when I accidentally rotate to Landscape and then go back to Portrait within a second to try and resume what I was doing in build 565.

Unfortunately, after the Landscape rotation, Ishtar immediately discards my old Portrait position and resets me to some arbitrary place in my inventory.

Given my { Hunter, Warlock, Titan, Vault } pages, I tested:

- Start at Titan Ships, rotate to landscape, rotate to portrait, now at Hunter Consumables.
- Start at Titan Legs, rotate, rotate, now at Hunter Chest Armor.
- Start at Warlock Subclass, rotate, rotate, now at Hunter Subclass.
- Start at Vault Artifacts, rotate, rotate, now at Hunter Gauntlets.

I wouldn't mind so much if it would wait a second or two before forgetting my place, or only returned to the place it was at if no scrolling has occurred, or anything like that.

**Comment by designker** [comment]
There are various issues that make this too much work to fix. I did try, but won't revisit this again.
