### ISSUE TITLE
Tapping subclass icons rapidly makes one of the subclasses disappear.

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#52]
While frantically tapping at the new subclass functionality back in June, I was able to expose a bug where two of the subclasses turn into Void or Arc or whatever. Both of the duplicate subclass buttons work as expected, so at least they're wired up such that the image matches the backing objects, but it's still odd. Last reproduced in build 565.

**Comment by designker** [comment]
should be fixed

**Comment by floatingatoll** [comment]
Verified in 573, thanks!
