### ISSUE TITLE
Armsday package don't have the same gold borders as Destiny

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#55]
Armsday packages in Destiny seem to have gold borders when a package of a specific type (e.g. ARI-45) was owned by the character when Tuesday reset occurs. In that scenario, both the original package owned by the character, and a replacement package purchased after claiming one of the options, will have a gold border until the next reset.

Ishtar does not, as of build 565, show a gold border on Armsday packages that meet this requirement.

**Comment by designker** [comment]
Fixed in the next version

**Comment by floatingatoll** [comment]
My long-winded thing no longer appears correct, BTW. All of my Armsday packages are gold-bordered, whether bought or rebought this week or last. Ishtar does the right thing and gold-borders all of them as of 573. Thank you!
