### ISSUE TITLE
Character experience bar is stuck at 0%

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#56]
The experience bar overlaid on each character's current emblem always shows 0%. Last verified in build 565.

![Experience bar](https://cloud.githubusercontent.com/assets/92684/16935459/87fa7bcc-4d14-11e6-9ac2-3a16de46fffc.png)

**Comment by designker** [comment]
Just like it in the Destiny UI.

**Comment by floatingatoll** [comment]
Huh, so it is. Got confused by the motes progress bar. Sorry!
