### ISSUE TITLE
"Maximize light to" and "🔸334" have different baselines.

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#57]
In the Loadouts pane, the text on the Maximize light button has a vertical alignment mismatch between "Maximize light to" and "🔸334". Last verified in build 565.

![Button](https://cloud.githubusercontent.com/assets/92684/16935502/d60cb01e-4d14-11e6-88e4-b3d57c1e970b.png)

**Comment by designker** [comment]
Fixed in the next build. The font was also a slightly different size.

**Comment by floatingatoll** [comment]
Verified in 573, thanks!
