### ISSUE TITLE
Overline variation between Armor and Weapons/Inventory/Progress selectors.

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#58]
For some reason, the Armor selector in build 565 on my 6S has a wider overline than the Weapons/Inventory/Progress selectors. This may be related to why the overline above Weapons and Progress doesn't extend to the edge of the screen in portrait.

![armor](https://cloud.githubusercontent.com/assets/92684/16935558/5b640870-4d15-11e6-9547-14d0778bc634.png)

![weapons](https://cloud.githubusercontent.com/assets/92684/16935561/5e76609e-4d15-11e6-8455-40da2ac7a845.png)

![inventory](https://cloud.githubusercontent.com/assets/92684/16935565/62309416-4d15-11e6-8476-6289190f326c.png)

![progress](https://cloud.githubusercontent.com/assets/92684/16935567/64fe3afe-4d15-11e6-9d0c-e5730ca26587.png)

**Comment by designker** [comment]
Yes it is fixed size
