### ISSUE TITLE
Horizontal rule separator missing on Sterling Treasure rewards at light level 3

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#59]
When the Sterling Treasure rewards are at light level 3, the horizontal rule separating the description text and the perk bubbles is missing.

![3 light](https://cloud.githubusercontent.com/assets/92684/16935641/f9ae8136-4d15-11e6-819c-9a80351b414b.png)

![300 light](https://cloud.githubusercontent.com/assets/92684/16935644/fff2c606-4d15-11e6-8f02-7250c2ca88c3.png)

**Comment by designker** [comment]
Looks just like this in the game
