### ISSUE TITLE
Color perk is shown incorrectly when light 3 sterling treasure rewards are leveled

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#60]
As best as I can tell, on build 565, if you level experience into a Spektar light 3 armor piece from a Sterling Treasure, but neither unlock perks nor infuse a higher-level item into it, then Ishtar will show the color bubble incorrectly.

Three examples of three ways the color perk bubble are shown in Ishtar follow. I believe only two of them are correct, since the color perk is either active or inactive, but is always leveled upon receipt of the light 3 item.

![photo_ - 3 1](https://cloud.githubusercontent.com/assets/92684/16935818/3b7ecd72-4d17-11e6-8a88-beb872fd8779.png)
![photo_ - 1 12](https://cloud.githubusercontent.com/assets/92684/16935820/3bafdae8-4d17-11e6-9066-049d8d734823.png)
![photo_ - 2 4](https://cloud.githubusercontent.com/assets/92684/16935819/3bacebb2-4d17-11e6-9749-b781a957fea3.png)

**Comment by designker** [comment]
fixed in next build

**Comment by floatingatoll** [comment]
Build 573 fixes the display of the "color filled in" perk node to include the cool gray inset border, which I completely missed in-game.

However, the first screenshot (green border, gray circle, color not selected) does not match in-game, where there is no green border.

**Comment by floatingatoll** [comment]
Clarification, based on your Slack question: Spektar Green is fixed. Spektar Magenta is not.

**Comment by floatingatoll** [comment]
Verified fixed in 574, thanks!
