### ISSUE TITLE
Sparrow text is missing platform-specific icons (L2, R2, X, etc.)

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#61]
This is extremely low priority.

The sparrow text is missing the platform-specific icons (L2, R2, X, etc.) as of build 565 and basically forever ago. This is not an urgent issue, since the specific buttons are only useful in the actual game. The official companion app does no better at this.

**Comment by designker** [comment]
No way to fix. There are no characters in the manifest that can be parsed and no font that contains this characters available. I once asked Bugnie about it and it seems this will never be addressed. It could never be 100% as you cannot know how peoples controllers are mapped.
