### ISSUE TITLE
Rotating between portrait and landscape closes non-Transfer views.

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#62]
When rotating either direction between portrait and landscape on my 6S, all non-Transfer views are closed (Details, Armsday) as of build 565.

**Comment by Wh1rledPeas** [comment]
I have noticed some odd behavior here also. I'm on a Galaxy S6 and sometimes I'm looking at one Guardian's armor/weapons/etc. and I turn my phone accidentally, switching to landscape mode, so I rotate it back and then I'm looking at the vault... 

Perhaps a "save last state" feature would provide a better user experience, when switching back to portrait mode?

**Comment by designker** [comment]
Not going to fix. There are some edge cases that just go away with this behavior even if it is a bit annoying
