### ISSUE TITLE
Armsday packages lack the armsday iconography in the background

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#63]
When viewing various sections of the app, the background shifts to match the displayed content (hunter, warlock, titan, and especially Vault). However, the armsday packages show no such background, even though two specific iconographies (a diamond with four loops, a tessellating grid-like background of diamonds) exist for the Armsday packages in actual Destiny.

![Armsday](https://cloud.githubusercontent.com/assets/92684/16936118/1d7bc530-4d19-11e6-9c27-ea7ed021d8f2.png)

**Comment by designker** [comment]
Not going to fix
