### ISSUE TITLE
Checklists: Trials is a centered row, Nightfall is not a centered row

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#64]
When looking at the Checklist pane, either in portrait or landscape on build 565 on the 6S, the Nightfall checklist is left-aligned, but the Trials checklist is center-aligned.

![Alignments](https://cloud.githubusercontent.com/assets/92684/16936208/cb4c5f8a-4d19-11e6-8c6d-f82cbbbd8619.png)

**Comment by designker** [comment]
This is intentional. I will add the other items such as heroics and dailies in 1.6
