### ISSUE TITLE
After logging out, some login steps ignore audio options

### ISSUE THREAD

**Issue by stevennic22** [designker/ishtar-commander-bugs#65]
While logged in, audio has been disabled. After logging out, the 'Good evening Dr. Shim' audio remains disabled. Failing to properly login would be expected to also be silent, but the 'Security breach' audio plays anyways.

Device: iPhone 6 (9.0.2)
Build: 568

STR:

1. Log into Ishtar
2. Disable audio
3. Log out of Ishtar
4. Open either XB or PS login windows
5. Click 'Done' to close webview and cause login to fail

Result: "Dr. Shim, security breach!" plays no matter what. It does obey the iOS mute switch though, which is nice.

**Comment by designker** [comment]
Fixed in the next build
