### ISSUE TITLE
Users can't find the Donate link.

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#67]
There are app reviews and reddit posts indicating that users can't figure out how to donate money to Ishtar. The only way to do so is buried inside the About dialog, with the invisibly-clickable Patreon link. 

Could you add a [DONATE] button below the [ABOUT] button in the settings pane, above the language flags, so that users can more readily discover it?

(Not [PATREON], because 99 out of 100 people will know what Donate means, but not what Patreon means.)

**Comment by floatingatoll** [comment]
(I am one of those users, incidentally. Couldn't find the link in the app until someone told me where to find it.)

**Comment by floatingatoll** [comment]
App reviews quotes:

> I'm grateful it's free, but I'd pay for it!

> Only thing its missing is a donate button. Edit: seriously. Where can we donate to you and support this amazing app?

> And I am sure if you made a paid version of this many of us would support it (myself included).

**Comment by floatingatoll** [comment]
Reddit quotes:

> Literally the only feedback I would offer - and this is kind of weird - is that you should make it easier for people like me to donate!

> Is there a way that we can donate to support your work here?

> Is there a way to donate? i would legitimately give you $5 to pay for this app

> No special permissions, no ads, no cost, surely you can provide us with a link to donate!

> I'd happily pay for your application, and that is something I don't usually say. Amazing app and support

> I would be willing to pay for it, that's how useful it is.

> If you have direct paypal or credit card donation method let me know.

> If I could offer one small piece of advice, you should definitely add a donate button through PayPal on the app. I, and I know I'm not alone, would be more than happy to send money your way for all that you've done/continue to do.

**Comment by floatingatoll** [comment]
UI mockup:

![DONATE](https://cloud.githubusercontent.com/assets/92684/17041230/8ee1ca84-4f59-11e6-8a78-0d9989be6fcd.png)

**Comment by floatingatoll** [comment]
Staring at that UX mockup, you might could the about/donate buttons the same size as the On/Off buttons, and align them with the on/off pair to their left, maybe with a header or something.

**Comment by Wh1rledPeas** [comment]
I agree with floatingatol. I may be a bit OCD about things, but the more "in line" the buttons are, the cleaner the interface looks.

**Comment by designker** [comment]
This won't be happening. Donate buttons that are not directly linked to an in-app purchase are an instant app rejection. Part of the current design benefits are apple have not noticed it.

**Comment by designker** [comment]
I should add that in the next release I will redesign this dialog, but this kind of issue is not a concern for me. I am grateful for the pateons that support the app but expending mental effort to chase a few more dollars isn't what motivates me around this app.
