### ISSUE TITLE
Settings dialog text extends beyond overline

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#68]
In the below screenshot, the overline for "ARMOR GRADES" isn't long enough to cover the text (and is wider than the buttons, unlike the rest).

![OVERLINE](https://cloud.githubusercontent.com/assets/92684/17041477/2743b098-4f5b-11e6-887b-18f1f7dc30f8.png)

**Comment by designker** [comment]
Not going to fix as settings will be redesigned in 1.6
