### ISSUE TITLE
Settings dialog large buttons are horizontally offset a couple pixels from small buttons

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#69]
The LOG OUT, FULL REFRESH, and ABOUT buttons are all offset a couple pixels left of the grid the other (smaller) buttons are using.

![Offset](https://cloud.githubusercontent.com/assets/92684/17041523/5bdc6f5c-4f5b-11e6-83c6-7c8a746ebae3.png)

**Comment by designker** [comment]
Marking as closed as in 1.6 setting will be totally redesigned.
