### ISSUE TITLE
Users think "Destiny servers are not available" means broken app

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#70]
When Ishtar receives error 5 from the Bungie API (maintenance mode), it displays the screenshot below, a direct quote of the text from the Destiny app itself. Unfortunately, users blame this error on the app, rather than on Bungie, when the app knows with absolute certainty that the issue is at Bungie.

Consider altering this error in some fashion to contain any of:

- Declare specific responsibility of the problem as not-the-app: "Bungie says", "Bungie has"
- Replace "are not available" with a more specific statement of the issue: "are offline for maintenance", "are not available due to maintenance"
- Request and display an ANIMAL code from Bungie through the API forums, to be used by app developers when the API is in maintenance mode.

![API maintenance mode](https://cloud.githubusercontent.com/assets/92684/17041668/792cf18e-4f5c-11e6-891f-bd0ce43bb144.png)

**Comment by designker** [comment]
Fixed
