### ISSUE TITLE
"Destiny servers not available" dialog permits refreshing rapidly

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#71]
When the API returns error code 5, Ishtar puts up a specific error page indicating the (known) problem.

Tapping the dialog triggers an immediate refresh, with no delay whatsoever. Tapping the dialog repeatedly (in frustration at the outage) appears to trigger a series of immediate refreshes. This is, perhaps, more refreshes than the Destiny servers wish to accept.

Consider adding a brief delay somewhere in the process so that users are capped at no more than one request per second when viewing this dialog.

![API down](https://cloud.githubusercontent.com/assets/92684/17041727/e80ed144-4f5c-11e6-8de2-e848f6368a86.png)

**Comment by designker** [comment]
Wont fix
