### ISSUE TITLE
Feature Request: Item specific refresh buttons

### ISSUE THREAD

**Issue by Wh1rledPeas** [designker/ishtar-commander-bugs#73]
Not sure if it is acceptable to post feature requests here. Just let me know, if not. 

But... T save on the amount of refreshing, I think it would be beneficial to have a refresh button per group of items. (i.e. Primary, Secondary, Heavy, Ghosts, etc.)

Many times I am getting drops in game and feeling the need to check their T-12 rating before I decide to dismantle/infuse. Most times, it's a single item. (a ghost or a pair of gauntlets, etc.) So all I really need to do is refresh that section, to do a quick refresh, so the new item shows up.

If Bungie provides a push notification, that would be tons better, but in absence of that, I way to quickly refresh only the items I need to work with, would cut down significantly on the amount of refreshing. 

Perhaps a small refresh icon to right justified on the section header line?

**Comment by designker** [comment]
It is simpler to just refresh everything

**Comment by Wh1rledPeas** [comment]
I realize it's simpler, but it takes longer, uses more bandwidth on the API, and locks up, spinning the refresh icon for minutes at a time... 

Just thought this feature might be more user friendly, and remove frustration...
