### ISSUE TITLE
Special characters not capitalized properly

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#78]
Somewhat related to issue #45,  but some special characters are still not capitalized as they should be as the names of weapons/armor (as of build 575).
The only ones I am currently able to verify are **Fang of Ir Yût** and **Façade of the Hezen Lords**. The special character in each of those names is lower-case while the rest of the name is upper-case. Although I have seen screenshots elsewhere that seem like it works fine for the "Ä" in Häkke.
This may also affect the names of weapon/armor perks, as those are also shown in app as capitalized.

**Comment by designker** [comment]
I have to fix this on a letter by letter approach due to limits in the framework I use. So keep on reporting new ones as you find them. These 2 characters are fixed in the next build
