### ISSUE TITLE
Cancel a Pull-to-refresh

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#79]
This is more of a pet peeve, but is it possible to only trigger pull to refresh on release?

This way, if I notice I've gone too far, I can scroll back down before letting go so as to not trigger the refresh.

The way it is now, I occasionally scroll up too high and accidentally trigger a refresh. Again, only a minor annoyance, but I've seen other apps allow you to back out of a pull to refresh and thought it might be beneficial here.

**Comment by designker** [comment]
Can you give me an example app to download so I can see how they do it?

**Comment by alexxnz** [comment]
Looking for examples on iOS and I was surprised that most apps there don't have this functionality.

I know Inbox from Google functions in this way on both Android and iOS. I presume Gmail does as well, although I can only verify this on Android.

**Comment by cowgod** [comment]
Yep, Gmail for iOS does this as well.

**Comment by designker** [comment]
Pull to refresh is basically a hack. There is no way I am spending the time to make cancel work. I spent a few minutes looking into this and it is clear it would be an epic waste of time to take it further. Sorry about that.
