### ISSUE TITLE
Request: Animate refresh button on refresh

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#80]
Pressing the refresh button in the upper left-hand corner of the app currently gives no feedback that it's doing anything.
The only indication that a refresh is occurring shows in the lower right-hand corner of the app, and can be hard to see depending on what's on screen. It's also hard to see if you're using the phone with your right hand, in portrait, where your hand is covering where the notification would show.

Is it possible to animate the refresh icon to spin while it's refreshing?

**Comment by designker** [comment]
fixed in next version
