### ISSUE TITLE
Android: Text cursor is pink

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#81]
I'm unsure if this is intentional or not, but just so you're aware, highlighting text fields in Android uses a pink cursor (screenshot below)
I believe this is part of the material design where apps can customize color schemes. Not sure if this occurs in older Android OSes (I'm currently on 6.0.1)

![screenshot_20160725-143744](https://cloud.githubusercontent.com/assets/16849366/17112957/4b54d7fa-5276-11e6-9a77-f43d14dd3900.png)

**Comment by designker** [comment]
This is partly stuff that won't be fixed in the framework I use for some time and part stuff I don't want to touch as it so easily breaks older versions of Android the app currently runs on.
