### ISSUE TITLE
Login pages always in English regardless of language selected in Ishtar

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#83]
Someone reported on Slack that the login pages are always in English, regardless of the language selected in Ishtar before logging in.

**Comment by floatingatoll** [comment]
PSN requires an HTTP header ```Accept-Language: de``` (or ```ja```, or ```es```) to present the correct language at the existing login URL.

```
$ curl -s https://auth.api.sonyentertainmentnetwork.com/login.jsp | grep '<title>'
<title>Sign In: Sony Entertainment Network</title>
$ curl -H 'Accept-Language: de' -s ...
<title>Anmelden: Sony Entertainment Network</title>
$ curl -H 'Accept-Language: ja' -s ...
<title>サインイン: Sony Entertainment Network</title>
$ curl -H 'Accept-Language: es' -s ...
<title>Iniciar sesión: Sony Entertainment Network</title>
```

**Comment by floatingatoll** [comment]
A complete list of language two-letter acronyms accepted in the ```Accept-Language``` header is maintained at http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

**Comment by floatingatoll** [comment]
Looks like PSN takes ```https://auth.api.sonyentertainmentnetwork.com/login.jsp?request_locale=de_DE``` (thanks, unnamed Slack person!)

**Comment by floatingatoll** [comment]
Verified that ```de_DE```, ```ja_JA```, ```es_ES``` all work as expected in that PSN url.

**Comment by designker** [comment]
Fixed already. Please verify and close

**Comment by lostyBO** [comment]
This is fixed. Please close.

**Comment by floatingatoll** [comment]
Verified fixed for 5 of 6 languages. As of build 585, the flag of Spain takes me to an English login page.

**Comment by designker** [comment]
Verify latest version. Should be fixed

**Comment by floatingatoll** [comment]
Verified fixed for all 7 languages
