### ISSUE TITLE
Subclass names bleed over to the adjacent column

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#94]
Particularly with the German and Spanish versions of the subclass names, these longer names spill over to the adjacent column in portrait mode.
In landscape, the subclass name just about touches the adjacent subclass icons.

![slack for ios upload](https://cloud.githubusercontent.com/assets/16849366/17180059/2c68661c-53e9-11e6-8352-4d9345a10d62.jpg)

**Comment by designker** [comment]
Verify fixed

**Comment by alexxnz** [comment]
Verified in build 588
