### ISSUE TITLE
Subclass details has a rarity level of Common

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#95]
I'm not sure that subclasses should have a rarity level associated with them.
(On a separate note, should subclasses be enabled for swipe comparison? They currently are not)

I've included an in-game screen of the closest equivalent pop-up for the subclasses.

![destiny_20160726163606](https://cloud.githubusercontent.com/assets/16849366/17180414/68fc7cde-53ea-11e6-8eb3-b61b81a57e79.jpg)

**Comment by floatingatoll** [comment]
Issue confirmed in build 591.

**Comment by designker** [comment]
fixed
