### ISSUE TITLE
Padding for armor stats is too low

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#99]
The padding for the armor stats between the two horizontal rules is lower than what it should be.

Padding for weapon stats seem to fall in line with what is shown in-game. Screenshots below for armor and weapon pop-ups

Build 579

![armor](https://cloud.githubusercontent.com/assets/16849366/17189454/88bc6bea-540f-11e6-9502-4018f5f6608f.PNG)
![weapon](https://cloud.githubusercontent.com/assets/16849366/17189459/8c0027d8-540f-11e6-92db-2f3d3bb1caf8.PNG)

**Comment by floatingatoll** [comment]
When I last checked on ~560, there's also a padding variation in this
specific location when turning the armor gradings bar on and off in
preferences.

**Comment by designker** [comment]
Fixed
